/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* top =  1  */
/* src = "mai.v:1.1-7.10" */
module mai(a, b, eq, gt, lt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  /* src = "mai.v:1.18-1.19" */
  input a;
  wire a;
  /* src = "mai.v:1.27-1.28" */
  input b;
  wire b;
  /* src = "mai.v:1.37-1.39" */
  output eq;
  wire eq;
  /* src = "mai.v:1.48-1.50" */
  output gt;
  wire gt;
  /* src = "mai.v:1.59-1.61" */
  output lt;
  wire lt;
  NOT _04_ (
    .A(a),
    .Y(_01_)
  );
  NOT _05_ (
    .A(b),
    .Y(_02_)
  );
  OR _06_ (
    .A(a),
    .B(_02_),
    .Y(_03_)
  );
  NOT _07_ (
    .A(_03_),
    .Y(lt)
  );
  OR _08_ (
    .A(_01_),
    .B(b),
    .Y(_00_)
  );
  NOT _09_ (
    .A(_00_),
    .Y(gt)
  );
  AND _10_ (
    .A(_03_),
    .B(_00_),
    .Y(eq)
  );
endmodule
