/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "comparator17.v:1.1-10.10" */
module comparator17(a, b, L, E, G);
wire _00_;
wire _01_;
wire _02_;
wire _03_;
output E;
wire E;
output G;
wire G;
output L;
wire L;
input a;
wire a;
input b;
wire b;

not _04_ ( .Y(_01_), .A(a));

not _05_ (.Y(_02_), .A(b));

OR _06_ (.Y(_03_), .A(a),.B(_02_));

not _07_ ( .Y(L), .A(_03_));

OR _08_ (.Y(_00_), .A(_01_), .B(b));

not _09_ ( .Y(G), .A(_00_));

AND _10_ ( .Y(E), .A(_03_), .B(_00_));
endmodule


