/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* top =  1  */
/* src = "pe_circuit7.v:1.1-13.10" */
module pe_circuit7(A0, A1, Y0, Y1, Y2, Y3);
  /* src = "pe_circuit7.v:4.8-4.10" */
  output A0;
  wire A0;
  /* src = "pe_circuit7.v:4.12-4.14" */
  output A1;
  wire A1;
  /* src = "pe_circuit7.v:3.7-3.9" */
  input Y0;
  wire Y0;
  /* src = "pe_circuit7.v:3.11-3.13" */
  input Y1;
  wire Y1;
  /* src = "pe_circuit7.v:3.15-3.17" */
  input Y2;
  wire Y2;
  /* src = "pe_circuit7.v:3.19-3.21" */
  input Y3;
  wire Y3;
  OR _0_ (
    .A(Y3),
    .B(Y2),
    .Y(A1)
  );
  WIRE _1_ (
    .A(Y1),
    .Z(A0)
  );
endmodule
