/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "and14.v:2.1-11.10" */
module and14(a, b, out);
  /* src = "and14.v:3.22-3.23" */
  input [2:0] a;
  wire [2:0] a;
  /* src = "and14.v:4.22-4.23" */
  input [2:0] b;
  wire [2:0] b;
  /* src = "and14.v:5.22-5.25" */
  output [2:0] out;
  wire [2:0] out;
  AND _0_ (
    .A(a[0]),
    .B(b[0]),
    .Y(out[0])
  );
  AND _1_ (
    .A(a[1]),
    .B(b[1]),
    .Y(out[1])
  );
  AND _2_ (
    .A(a[2]),
    .B(b[2]),
    .Y(out[2])
  );
endmodule
