/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "and23.v:3.1-15.10" */
module and23(a, b, c, d, e, f, out);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  /* src = "and23.v:4.9-4.10" */
  input a;
  wire a;
  /* src = "and23.v:5.9-5.10" */
  input b;
  wire b;
  /* src = "and23.v:6.9-6.10" */
  input c;
  wire c;
  /* src = "and23.v:7.9-7.10" */
  input d;
  wire d;
  /* src = "and23.v:8.9-8.10" */
  input e;
  wire e;
  /* src = "and23.v:9.9-9.10" */
  input f;
  wire f;
  /* src = "and23.v:10.10-10.13" */
  output out;
  wire out;
  AND _4_ (
    .A(a),
    .B(b),
    .Y(_2_)
  );
  AND _5_ (
    .A(c),
    .B(d),
    .Y(_3_)
  );
  AND _6_ (
    .A(e),
    .B(f),
    .Y(_0_)
  );
  AND _7_ (
    .A(_3_),
    .B(_0_),
    .Y(_1_)
  );
  AND _8_ (
    .A(_2_),
    .B(_1_),
    .Y(out)
  );
endmodule
