/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "and24.v:3.1-16.10" */
module and24(a, b, c, d, e, f, g, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  /* src = "and24.v:4.9-4.10" */
  input a;
  wire a;
  /* src = "and24.v:5.9-5.10" */
  input b;
  wire b;
  /* src = "and24.v:6.9-6.10" */
  input c;
  wire c;
  /* src = "and24.v:7.9-7.10" */
  input d;
  wire d;
  /* src = "and24.v:8.9-8.10" */
  input e;
  wire e;
  /* src = "and24.v:9.9-9.10" */
  input f;
  wire f;
  /* src = "and24.v:10.9-10.10" */
  input g;
  wire g;
  /* src = "and24.v:11.10-11.13" */
  output out;
  wire out;
  AND _05_ (
    .A(e),
    .B(f),
    .Y(_04_)
  );
  AND _06_ (
    .A(g),
    .B(_04_),
    .Y(_00_)
  );
  AND _07_ (
    .A(a),
    .B(b),
    .Y(_01_)
  );
  AND _08_ (
    .A(c),
    .B(d),
    .Y(_02_)
  );
  AND _09_ (
    .A(_01_),
    .B(_02_),
    .Y(_03_)
  );
  AND _10_ (
    .A(_00_),
    .B(_03_),
    .Y(out)
  );
endmodule
