/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "comparator14.v:1.1-35.10" */
module comparator14(Data_in_A, Data_in_B, less, equal, greater);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  /* src = "comparator14.v:10.17-10.26" */
  input [3:0] Data_in_A;
  wire [3:0] Data_in_A;
  /* src = "comparator14.v:11.17-11.26" */
  input [3:0] Data_in_B;
  wire [3:0] Data_in_B;
  /* src = "comparator14.v:14.16-14.21" */
  output equal;
  wire equal;
  /* src = "comparator14.v:15.16-15.23" */
  output greater;
  wire greater;
  /* src = "comparator14.v:13.16-13.20" */
  output less;
  wire less;
  not _40_ (
    .A(Data_in_A[0]),
    .Y(_00_)
  );
  not _41_ (
    .A(Data_in_A[1]),
    .Y(_01_)
  );
  not _42_ (
    .A(Data_in_A[2]),
    .Y(_02_)
  );
  not _43_ (
    .A(Data_in_A[3]),
    .Y(_03_)
  );
  not _44_ (
    .A(Data_in_B[0]),
    .Y(_04_)
  );
  not _45_ (
    .A(Data_in_B[1]),
    .Y(_05_)
  );
  not _46_ (
    .A(Data_in_B[2]),
    .Y(_06_)
  );
  not _47_ (
    .A(Data_in_B[3]),
    .Y(_07_)
  );
  AND _48_ (
    .A(_00_),
    .B(Data_in_B[0]),
    .Y(_08_)
  );
  AND _49_ (
    .A(_03_),
    .B(Data_in_B[3]),
    .Y(_09_)
  );
  OR _50_ (
    .A(Data_in_A[3]),
    .B(_07_),
    .Y(_10_)
  );
  AND _51_ (
    .A(_02_),
    .B(Data_in_B[2]),
    .Y(_11_)
  );
  OR _52_ (
    .A(Data_in_A[2]),
    .B(_06_),
    .Y(_12_)
  );
  AND _53_ (
    .A(_10_),
    .B(_12_),
    .Y(_13_)
  );
  OR _54_ (
    .A(_09_),
    .B(_11_),
    .Y(_14_)
  );
  AND _55_ (
    .A(Data_in_A[2]),
    .B(_06_),
    .Y(_15_)
  );
  OR _56_ (
    .A(_02_),
    .B(Data_in_B[2]),
    .Y(_16_)
  );
  AND _57_ (
    .A(Data_in_A[3]),
    .B(_07_),
    .Y(_17_)
  );
  OR _58_ (
    .A(_03_),
    .B(Data_in_B[3]),
    .Y(_18_)
  );
  AND _59_ (
    .A(_16_),
    .B(_18_),
    .Y(_19_)
  );
  OR _60_ (
    .A(_15_),
    .B(_17_),
    .Y(_20_)
  );
  AND _61_ (
    .A(_13_),
    .B(_19_),
    .Y(_21_)
  );
  OR _62_ (
    .A(_14_),
    .B(_20_),
    .Y(_22_)
  );
  AND _63_ (
    .A(Data_in_A[1]),
    .B(_05_),
    .Y(_23_)
  );
  OR _64_ (
    .A(_01_),
    .B(Data_in_B[1]),
    .Y(_24_)
  );
  AND _65_ (
    .A(_01_),
    .B(Data_in_B[1]),
    .Y(_25_)
  );
  OR _66_ (
    .A(Data_in_A[1]),
    .B(_05_),
    .Y(_26_)
  );
  AND _67_ (
    .A(Data_in_A[0]),
    .B(_04_),
    .Y(_27_)
  );
  OR _68_ (
    .A(_00_),
    .B(Data_in_B[0]),
    .Y(_28_)
  );
  AND _69_ (
    .A(_24_),
    .B(_28_),
    .Y(_29_)
  );
  OR _70_ (
    .A(_23_),
    .B(_27_),
    .Y(_30_)
  );
  AND _71_ (
    .A(_26_),
    .B(_29_),
    .Y(_31_)
  );
  OR _72_ (
    .A(_25_),
    .B(_30_),
    .Y(_32_)
  );
  AND _73_ (
    .A(_21_),
    .B(_31_),
    .Y(_33_)
  );
  OR _74_ (
    .A(_22_),
    .B(_32_),
    .Y(_34_)
  );
  OR _75_ (
    .A(_08_),
    .B(_34_),
    .Y(_35_)
  );
  not _76_ (
    .A(_35_),
    .Y(equal)
  );
  AND _77_ (
    .A(_21_),
    .B(_25_),
    .Y(_36_)
  );
  AND _78_ (
    .A(_14_),
    .B(_18_),
    .Y(_37_)
  );
  OR _79_ (
    .A(_36_),
    .B(_37_),
    .Y(_38_)
  );
  OR _80_ (
    .A(_33_),
    .B(_38_),
    .Y(_39_)
  );
  not _81_ (
    .A(_39_),
    .Y(greater)
  );
  AND _82_ (
    .A(_35_),
    .B(_39_),
    .Y(less)
  );
endmodule
