/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "comparator21.v:1.1-7.10" */
module comparator21(a0, a1, b0, b1, eq, gt, lt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  /* src = "comparator21.v:1.28-1.30" */
  input a0;
  wire a0;
  /* src = "comparator21.v:1.37-1.39" */
  input a1;
  wire a1;
  /* src = "comparator21.v:1.47-1.49" */
  input b0;
  wire b0;
  /* src = "comparator21.v:1.56-1.58" */
  input b1;
  wire b1;
  /* src = "comparator21.v:1.67-1.69" */
  output eq;
  wire eq;
  /* src = "comparator21.v:1.78-1.80" */
  output gt;
  wire gt;
  /* src = "comparator21.v:1.89-1.91" */
  output lt;
  wire lt;
  not _16_ (
    .A(a0),
    .Y(_14_)
  );
  not _17_ (
    .A(a1),
    .Y(_15_)
  );
  not _18_ (
    .A(b0),
    .Y(_00_)
  );
  not _19_ (
    .A(b1),
    .Y(_01_)
  );
  AND _20_ (
    .A(a0),
    .B(_00_),
    .Y(_02_)
  );
  OR _21_ (
    .A(_14_),
    .B(b0),
    .Y(_03_)
  );
  AND _22_ (
    .A(a1),
    .B(_01_),
    .Y(_04_)
  );
  OR _23_ (
    .A(_15_),
    .B(b1),
    .Y(_05_)
  );
  AND _24_ (
    .A(_03_),
    .B(_05_),
    .Y(_06_)
  );
  OR _25_ (
    .A(_02_),
    .B(_04_),
    .Y(_07_)
  );
  AND _26_ (
    .A(_14_),
    .B(b0),
    .Y(_08_)
  );
  OR _27_ (
    .A(a0),
    .B(_00_),
    .Y(_09_)
  );
  AND _28_ (
    .A(_15_),
    .B(b1),
    .Y(_10_)
  );
  OR _29_ (
    .A(a1),
    .B(_01_),
    .Y(_11_)
  );
  AND _30_ (
    .A(_09_),
    .B(_11_),
    .Y(_12_)
  );
  OR _31_ (
    .A(_08_),
    .B(_10_),
    .Y(_13_)
  );
  AND _32_ (
    .A(_06_),
    .B(_12_),
    .Y(eq)
  );
  AND _33_ (
    .A(_07_),
    .B(_11_),
    .Y(gt)
  );
  AND _34_ (
    .A(_05_),
    .B(_13_),
    .Y(lt)
  );
endmodule
