/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder24.v:1.1-13.10" */
module decoder24(din, en, dout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  /* src = "decoder24.v:2.15-2.18" */
  input [1:0] din;
  wire [1:0] din;
  /* src = "decoder24.v:4.16-4.20" */
  output [3:0] dout;
  wire [3:0] dout;
  /* src = "decoder24.v:3.9-3.11" */
  input en;
  wire en;
  not _04_ (
    .A(din[0]),
    .Y(_02_)
  );
  not _05_ (
    .A(din[1]),
    .Y(_03_)
  );
  AND _06_ (
    .A(_03_),
    .B(en),
    .Y(_00_)
  );
  AND _07_ (
    .A(_02_),
    .B(_00_),
    .Y(dout[0])
  );
  AND _08_ (
    .A(din[1]),
    .B(en),
    .Y(_01_)
  );
  AND _09_ (
    .A(_02_),
    .B(_01_),
    .Y(dout[1])
  );
  AND _10_ (
    .A(din[0]),
    .B(_00_),
    .Y(dout[2])
  );
  AND _11_ (
    .A(din[0]),
    .B(_01_),
    .Y(dout[3])
  );
endmodule
