/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "encoder14.v:1.1-13.10" */
module encoder14(din, dout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  /* src = "encoder14.v:2.13-2.16" */
  input [3:0] din;
  wire [3:0] din;
  /* src = "encoder14.v:3.18-3.22" */
  output [1:0] dout;
  wire [1:0] dout;
  OR _11_ (
    .A(din[2]),
    .B(din[0]),
    .Y(_08_)
  );
  not _12_ (
    .A(_08_),
    .Y(_09_)
  );
  AND _13_ (
    .A(din[3]),
    .B(din[1]),
    .Y(_10_)
  );
  not _14_ (
    .A(_10_),
    .Y(_00_)
  );
  OR _15_ (
    .A(din[3]),
    .B(din[1]),
    .Y(_01_)
  );
  AND _16_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  AND _17_ (
    .A(_09_),
    .B(_02_),
    .Y(dout[0])
  );
  OR _18_ (
    .A(din[3]),
    .B(din[2]),
    .Y(_03_)
  );
  OR _19_ (
    .A(din[1]),
    .B(din[0]),
    .Y(_04_)
  );
  AND _20_ (
    .A(din[3]),
    .B(din[2]),
    .Y(_05_)
  );
  OR _21_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  not _22_ (
    .A(_06_),
    .Y(_07_)
  );
  AND _23_ (
    .A(_03_),
    .B(_07_),
    .Y(dout[1])
  );
endmodule
