/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "encoder13.v:1.1-18.10" */
module encoder13(din, en, dout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  /* src = "encoder13.v:2.13-2.16" */
  input [3:0] din;
  wire [3:0] din;
  /* src = "encoder13.v:4.18-4.22" */
  output [1:0] dout;
  wire [1:0] dout;
  /* src = "encoder13.v:3.7-3.9" */
  input en;
  wire en;
  not _14_ (
    .A(din[2]),
    .Y(_12_)
  );
  not _15_ (
    .A(din[1]),
    .Y(_13_)
  );
  not _16_ (
    .A(din[0]),
    .Y(_00_)
  );
  AND _17_ (
    .A(_00_),
    .B(en),
    .Y(_01_)
  );
  AND _18_ (
    .A(_12_),
    .B(_01_),
    .Y(_02_)
  );
  OR _19_ (
    .A(din[3]),
    .B(din[1]),
    .Y(_03_)
  );
  AND _20_ (
    .A(din[3]),
    .B(din[1]),
    .Y(_04_)
  );
  not _21_ (
    .A(_04_),
    .Y(_05_)
  );
  AND _22_ (
    .A(_03_),
    .B(_05_),
    .Y(_06_)
  );
  AND _23_ (
    .A(_02_),
    .B(_06_),
    .Y(dout[0])
  );
  AND _24_ (
    .A(_13_),
    .B(_01_),
    .Y(_07_)
  );
  OR _25_ (
    .A(din[3]),
    .B(din[2]),
    .Y(_08_)
  );
  AND _26_ (
    .A(din[3]),
    .B(din[2]),
    .Y(_09_)
  );
  not _27_ (
    .A(_09_),
    .Y(_10_)
  );
  AND _28_ (
    .A(_08_),
    .B(_10_),
    .Y(_11_)
  );
  AND _29_ (
    .A(_07_),
    .B(_11_),
    .Y(dout[1])
  );
endmodule
