/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mult25.v:2.1-16.10" */
module mult25(x, y, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  /* src = "mult25.v:5.13-5.16" */
  output [3:0] out;
  wire [3:0] out;
  /* src = "mult25.v:3.12-3.13" */
  input [1:0] x;
  wire [1:0] x;
  /* src = "mult25.v:4.12-4.13" */
  input [1:0] y;
  wire [1:0] y;
  AND _06_ (
    .A(x[0]),
    .B(y[0]),
    .Y(out[0])
  );
  not _07_ (
    .A(out[0]),
    .Y(_00_)
  );
  AND _08_ (
    .A(x[1]),
    .B(y[1]),
    .Y(_01_)
  );
  AND _09_ (
    .A(_00_),
    .B(_01_),
    .Y(out[2])
  );
  AND _10_ (
    .A(x[0]),
    .B(y[1]),
    .Y(_02_)
  );
  AND _11_ (
    .A(y[0]),
    .B(x[1]),
    .Y(_03_)
  );
  AND _12_ (
    .A(_02_),
    .B(_03_),
    .Y(out[3])
  );
  not _13_ (
    .A(out[3]),
    .Y(_04_)
  );
  OR _14_ (
    .A(_02_),
    .B(_03_),
    .Y(_05_)
  );
  AND _15_ (
    .A(_04_),
    .B(_05_),
    .Y(out[1])
  );
endmodule
