/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mult10.v:1.1-5.10" */
module mult10(a, b, result);
  /* src = "mult10.v:1.22-1.23" */
  input a;
  wire a;
  /* src = "mult10.v:1.25-1.26" */
  input b;
  wire b;
  /* src = "mult10.v:2.20-2.26" */
  output result;
  wire result;
  AND _0_ (
    .A(a),
    .B(b),
    .Y(result)
  );
endmodule
