/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mux15.v:2.1-12.10" */
module mux15(a, b, sel, y);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "mux15.v:2.21-2.22" */
  input a;
  wire a;
  /* src = "mux15.v:2.24-2.25" */
  input b;
  wire b;
  /* src = "mux15.v:2.27-2.30" */
  input sel;
  wire sel;
  /* src = "mux15.v:3.32-3.33" */
  output y;
  wire y;
  not _3_ (
    .A(sel),
    .Y(_0_)
  );
  AND _4_ (
    .A(b),
    .B(sel),
    .Y(_1_)
  );
  AND _5_ (
    .A(a),
    .B(_0_),
    .Y(_2_)
  );
  OR _6_ (
    .A(_1_),
    .B(_2_),
    .Y(y)
  );
endmodule
