/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mux5.v:2.1-7.10" */
module mux5(in0, in1, sel, out);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "mux5.v:2.20-2.23" */
  input in0;
  wire in0;
  /* src = "mux5.v:2.31-2.34" */
  input in1;
  wire in1;
  /* src = "mux5.v:3.28-3.31" */
  output out;
  wire out;
  /* src = "mux5.v:2.42-2.45" */
  input sel;
  wire sel;
  not _3_ (
    .A(sel),
    .Y(_0_)
  );
  AND _4_ (
    .A(sel),
    .B(in1),
    .Y(_1_)
  );
  AND _5_ (
    .A(_0_),
    .B(in0),
    .Y(_2_)
  );
  OR _6_ (
    .A(_1_),
    .B(_2_),
    .Y(out)
  );
endmodule
