/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "nand10.v:2.1-10.10" */
module nand10(a, b, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  /* src = "nand10.v:3.22-3.23" */
  input [3:0] a;
  wire [3:0] a;
  /* src = "nand10.v:4.22-4.23" */
  input [3:0] b;
  wire [3:0] b;
  /* src = "nand10.v:5.23-5.26" */
  output [3:0] out;
  wire [3:0] out;
  not _04_ (
    .A(_02_),
    .Y(out[2])
  );
  AND _05_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_03_)
  );
  not _06_ (
    .A(_03_),
    .Y(out[3])
  );
  AND _07_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  not _08_ (
    .A(_00_),
    .Y(out[0])
  );
  AND _09_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_01_)
  );
  not _10_ (
    .A(_01_),
    .Y(out[1])
  );
  AND _11_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_02_)
  );
endmodule
