/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "nor22.v:2.1-11.10" */
module nor22(a, b, c, out);
  wire _0_;
  wire _1_;
  /* src = "nor22.v:3.9-3.10" */
  input a;
  wire a;
  /* src = "nor22.v:4.9-4.10" */
  input b;
  wire b;
  /* src = "nor22.v:5.9-5.10" */
  input c;
  wire c;
  /* src = "nor22.v:6.10-6.13" */
  output out;
  wire out;
  OR _2_ (
    .A(a),
    .B(b),
    .Y(_0_)
  );
  OR _3_ (
    .A(c),
    .B(_0_),
    .Y(_1_)
  );
  not _4_ (
    .A(_1_),
    .Y(out)
  );
endmodule
