/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "or26.v:1.1-11.10" */
module or26(a, b, c, d, out);
  wire _0_;
  wire _1_;
  /* src = "or26.v:2.9-2.10" */
  input a;
  wire a;
  /* src = "or26.v:3.9-3.10" */
  input b;
  wire b;
  /* src = "or26.v:4.9-4.10" */
  input c;
  wire c;
  /* src = "or26.v:5.9-5.10" */
  input d;
  wire d;
  /* src = "or26.v:6.10-6.13" */
  output out;
  wire out;
  OR _2_ (
    .A(a),
    .B(b),
    .Y(_0_)
  );
  OR _3_ (
    .A(c),
    .B(d),
    .Y(_1_)
  );
  OR _4_ (
    .A(_0_),
    .B(_1_),
    .Y(out)
  );
endmodule
