/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "or27.v:1.1-10.10" */
module or27(a, b, c, out);
  wire _0_;
  /* src = "or27.v:2.9-2.10" */
  input a;
  wire a;
  /* src = "or27.v:3.9-3.10" */
  input b;
  wire b;
  /* src = "or27.v:4.9-4.10" */
  input c;
  wire c;
  /* src = "or27.v:5.10-5.13" */
  output out;
  wire out;
  OR _1_ (
    .A(a),
    .B(b),
    .Y(_0_)
  );
  OR _2_ (
    .A(c),
    .B(_0_),
    .Y(out)
  );
endmodule
