/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "or7.v:1.1-9.10" */
module or7(a, b, out);
  /* src = "or7.v:2.22-2.23" */
  input [3:0] a;
  wire [3:0] a;
  /* src = "or7.v:3.22-3.23" */
  input [3:0] b;
  wire [3:0] b;
  /* src = "or7.v:4.23-4.26" */
  output [3:0] out;
  wire [3:0] out;
  OR _0_ (
    .A(a[0]),
    .B(b[0]),
    .Y(out[0])
  );
  OR _1_ (
    .A(a[1]),
    .B(b[1]),
    .Y(out[1])
  );
  OR _2_ (
    .A(a[2]),
    .B(b[2]),
    .Y(out[2])
  );
  OR _3_ (
    .A(a[3]),
    .B(b[3]),
    .Y(out[3])
  );
endmodule
