/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "sub6.v:2.1-19.10" */
module sub6(A, B, cin, sub, bo);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  /* src = "sub6.v:4.8-4.9" */
  input A;
  wire A;
  /* src = "sub6.v:4.10-4.11" */
  input B;
  wire B;
  /* src = "sub6.v:5.13-5.15" */
  output bo;
  wire bo;
  /* src = "sub6.v:4.12-4.15" */
  input cin;
  wire cin;
  /* src = "sub6.v:5.9-5.12" */
  output sub;
  wire sub;
  OR _12_ (
    .A(_08_),
    .B(B),
    .Y(_00_)
  );
  AND _13_ (
    .A(_08_),
    .B(B),
    .Y(_01_)
  );
  OR _14_ (
    .A(A),
    .B(_09_),
    .Y(_02_)
  );
  OR _15_ (
    .A(cin),
    .B(_01_),
    .Y(_03_)
  );
  AND _16_ (
    .A(_00_),
    .B(_03_),
    .Y(bo)
  );
  AND _17_ (
    .A(_00_),
    .B(_02_),
    .Y(_04_)
  );
  OR _18_ (
    .A(_11_),
    .B(_01_),
    .Y(_05_)
  );
  OR _19_ (
    .A(_10_),
    .B(_04_),
    .Y(_06_)
  );
  OR _20_ (
    .A(cin),
    .B(_05_),
    .Y(_07_)
  );
  AND _21_ (
    .A(_06_),
    .B(_07_),
    .Y(sub)
  );
  not _22_ (
    .A(A),
    .Y(_08_)
  );
  not _23_ (
    .A(B),
    .Y(_09_)
  );
  not _24_ (
    .A(cin),
    .Y(_10_)
  );
  AND _25_ (
    .A(A),
    .B(_09_),
    .Y(_11_)
  );
endmodule
