/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "xnor13.v:1.1-18.10" */
module xnor13(a, b, c, d, e, f, g, h, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  /* src = "xnor13.v:2.9-2.10" */
  input a;
  wire a;
  /* src = "xnor13.v:3.9-3.10" */
  input b;
  wire b;
  /* src = "xnor13.v:4.9-4.10" */
  input c;
  wire c;
  /* src = "xnor13.v:5.9-5.10" */
  input d;
  wire d;
  /* src = "xnor13.v:6.9-6.10" */
  input e;
  wire e;
  /* src = "xnor13.v:7.9-7.10" */
  input f;
  wire f;
  /* src = "xnor13.v:8.9-8.10" */
  input g;
  wire g;
  /* src = "xnor13.v:9.9-9.10" */
  input h;
  wire h;
  /* src = "xnor13.v:10.14-10.17" */
  output out;
  wire out;
  not _38_ (
    .A(_06_),
    .Y(_07_)
  );
  AND _39_ (
    .A(f),
    .B(e),
    .Y(_08_)
  );
  not _40_ (
    .A(_08_),
    .Y(_09_)
  );
  OR _41_ (
    .A(_07_),
    .B(_08_),
    .Y(_10_)
  );
  AND _42_ (
    .A(_06_),
    .B(_09_),
    .Y(_11_)
  );
  AND _43_ (
    .A(_04_),
    .B(_11_),
    .Y(_12_)
  );
  OR _44_ (
    .A(_05_),
    .B(_10_),
    .Y(_13_)
  );
  AND _45_ (
    .A(_05_),
    .B(_10_),
    .Y(_14_)
  );
  OR _46_ (
    .A(_04_),
    .B(_11_),
    .Y(_15_)
  );
  AND _47_ (
    .A(_13_),
    .B(_15_),
    .Y(_16_)
  );
  OR _48_ (
    .A(_12_),
    .B(_14_),
    .Y(_17_)
  );
  AND _49_ (
    .A(h),
    .B(g),
    .Y(_18_)
  );
  not _50_ (
    .A(_18_),
    .Y(_19_)
  );
  OR _51_ (
    .A(h),
    .B(g),
    .Y(_20_)
  );
  not _52_ (
    .A(_20_),
    .Y(_21_)
  );
  OR _53_ (
    .A(_18_),
    .B(_21_),
    .Y(_22_)
  );
  AND _54_ (
    .A(_19_),
    .B(_20_),
    .Y(_23_)
  );
  OR _55_ (
    .A(b),
    .B(a),
    .Y(_24_)
  );
  not _56_ (
    .A(_24_),
    .Y(_25_)
  );
  AND _57_ (
    .A(b),
    .B(a),
    .Y(_26_)
  );
  not _58_ (
    .A(_26_),
    .Y(_27_)
  );
  AND _59_ (
    .A(_24_),
    .B(_27_),
    .Y(_28_)
  );
  OR _60_ (
    .A(_25_),
    .B(_26_),
    .Y(_29_)
  );
  AND _61_ (
    .A(_23_),
    .B(_29_),
    .Y(_30_)
  );
  OR _62_ (
    .A(_22_),
    .B(_28_),
    .Y(_31_)
  );
  AND _63_ (
    .A(_22_),
    .B(_28_),
    .Y(_32_)
  );
  OR _64_ (
    .A(_23_),
    .B(_29_),
    .Y(_33_)
  );
  AND _65_ (
    .A(_31_),
    .B(_33_),
    .Y(_34_)
  );
  OR _66_ (
    .A(_30_),
    .B(_32_),
    .Y(_35_)
  );
  OR _67_ (
    .A(_17_),
    .B(_35_),
    .Y(_36_)
  );
  OR _68_ (
    .A(_16_),
    .B(_34_),
    .Y(_37_)
  );
  AND _69_ (
    .A(_36_),
    .B(_37_),
    .Y(out)
  );
  OR _70_ (
    .A(d),
    .B(c),
    .Y(_00_)
  );
  not _71_ (
    .A(_00_),
    .Y(_01_)
  );
  AND _72_ (
    .A(d),
    .B(c),
    .Y(_02_)
  );
  not _73_ (
    .A(_02_),
    .Y(_03_)
  );
  AND _74_ (
    .A(_00_),
    .B(_03_),
    .Y(_04_)
  );
  OR _75_ (
    .A(_01_),
    .B(_02_),
    .Y(_05_)
  );
  OR _76_ (
    .A(f),
    .B(e),
    .Y(_06_)
  );
endmodule
