/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "adder5.v:2.1-43.10" */
module adder5(A, B, Cin, Sum, Cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  /* src = "adder5.v:4.11-4.12" */
  input A;
  wire A;
  /* src = "adder5.v:4.13-4.14" */
  input B;
  wire B;
  /* src = "adder5.v:4.15-4.18" */
  input Cin;
  wire Cin;
  /* src = "adder5.v:5.20-5.24" */
  output Cout;
  wire Cout;
  /* src = "adder5.v:5.16-5.19" */
  output Sum;
  wire Sum;
  not _10_ (
    .A(B),
    .Y(_06_)
  );
  AND _11_ (
    .A(Cin),
    .B(A),
    .Y(_07_)
  );
  not _12_ (
    .A(_07_),
    .Y(_08_)
  );
  OR _13_ (
    .A(Cin),
    .B(A),
    .Y(_09_)
  );
  not _14_ (
    .A(_09_),
    .Y(_00_)
  );
  AND _15_ (
    .A(_08_),
    .B(_09_),
    .Y(_01_)
  );
  OR _16_ (
    .A(_07_),
    .B(_00_),
    .Y(_02_)
  );
  AND _17_ (
    .A(B),
    .B(_02_),
    .Y(_03_)
  );
  AND _18_ (
    .A(_06_),
    .B(_01_),
    .Y(_04_)
  );
  OR _19_ (
    .A(_03_),
    .B(_04_),
    .Y(Sum)
  );
  OR _20_ (
    .A(B),
    .B(_07_),
    .Y(_05_)
  );
  AND _21_ (
    .A(_09_),
    .B(_05_),
    .Y(Cout)
  );
endmodule
