/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "adder12.v:2.1-20.10" */
module adder12(A, B, S, C);
  wire _0_;
  wire _1_;
  /* src = "adder12.v:3.7-3.8" */
  input A;
  wire A;
  /* src = "adder12.v:3.10-3.11" */
  input B;
  wire B;
  /* src = "adder12.v:4.15-4.16" */
  output C;
  wire C;
  /* src = "adder12.v:4.12-4.13" */
  output S;
  wire S;
  AND _2_ (
    .A(A),
    .B(B),
    .Y(C)
  );
  NOT _3_ (
    .A(C),
    .Y(_0_)
  );
  OR _4_ (
    .A(A),
    .B(B),
    .Y(_1_)
  );
  AND _5_ (
    .A(_0_),
    .B(_1_),
    .Y(S)
  );
endmodule
