/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "adder14.v:2.1-26.10" */
module adder14(A, B, Sum, Cout);
  wire _0_;
  wire _1_;
  /* src = "adder14.v:3.11-3.12" */
  input A;
  wire A;
  /* src = "adder14.v:3.13-3.14" */
  input B;
  wire B;
  /* src = "adder14.v:4.20-4.24" */
  output Cout;
  wire Cout;
  /* src = "adder14.v:4.16-4.19" */
  output Sum;
  wire Sum;
  AND _2_ (
    .A(A),
    .B(B),
    .Y(Cout)
  );
  NOT _3_ (
    .A(Cout),
    .Y(_0_)
  );
  OR _4_ (
    .A(A),
    .B(B),
    .Y(_1_)
  );
  AND _5_ (
    .A(_0_),
    .B(_1_),
    .Y(Sum)
  );
endmodule
