/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "adder8.v:2.1-25.10" */
module adder8(A, B, S, C);
  /* src = "adder8.v:6.5-24.8" */
  wire _0_;
  /* src = "adder8.v:6.5-24.8" */
  wire _1_;
  wire _2_;
  wire _3_;
  /* src = "adder8.v:3.11-3.12" */
  input A;
  wire A;
  /* src = "adder8.v:3.14-3.15" */
  input B;
  wire B;
  /* src = "adder8.v:4.19-4.20" */
  output C;
  reg C;
  /* src = "adder8.v:4.16-4.17" */
  output S;
  reg S;
  AND _4_ (
    .A(B),
    .B(A),
    .Y(_0_)
  );
  NOT _5_ (
    .A(_0_),
    .Y(_2_)
  );
  OR _6_ (
    .A(B),
    .B(A),
    .Y(_3_)
  );
  AND _7_ (
    .A(_2_),
    .B(_3_),
    .Y(_1_)
  );
  /* src = "adder8.v:6.5-24.8" */
  always @*
    if (!1'h0) C = _0_;
  /* src = "adder8.v:6.5-24.8" */
  always @*
    if (!1'h0) S = _1_;
endmodule
