/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "adder11.v:2.1-40.10" */
module adder11(A, B, Cin, Sum, Cout);
  /* src = "adder11.v:6.5-39.8" */
  wire _00_;
  /* src = "adder11.v:6.5-39.8" */
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "adder11.v:3.11-3.12" */
  input A;
  wire A;
  /* src = "adder11.v:3.14-3.15" */
  input B;
  wire B;
  /* src = "adder11.v:3.17-3.20" */
  input Cin;
  wire Cin;
  /* src = "adder11.v:4.21-4.25" */
  output Cout;
  reg Cout;
  /* src = "adder11.v:4.16-4.19" */
  output Sum;
  reg Sum;
  OR _09_ (
    .A(B),
    .B(A),
    .Y(_07_)
  );
  AND _10_ (
    .A(B),
    .B(A),
    .Y(_08_)
  );
  AND _11_ (
    .A(Cin),
    .B(_07_),
    .Y(_02_)
  );
  OR _12_ (
    .A(_08_),
    .B(_02_),
    .Y(_00_)
  );
  NOT _13_ (
    .A(_00_),
    .Y(_03_)
  );
  OR _14_ (
    .A(Cin),
    .B(_07_),
    .Y(_04_)
  );
  AND _15_ (
    .A(Cin),
    .B(_08_),
    .Y(_05_)
  );
  AND _16_ (
    .A(_03_),
    .B(_04_),
    .Y(_06_)
  );
  OR _17_ (
    .A(_05_),
    .B(_06_),
    .Y(_01_)
  );
  /* src = "adder11.v:6.5-39.8" */
  always @*
    if (!1'h0) Sum = _01_;
  /* src = "adder11.v:6.5-39.8" */
  always @*
    if (!1'h0) Cout = _00_;
endmodule
