/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "adder13.v:2.1-10.10" */
module adder13(A, B, Cin, Sum, Cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  /* src = "adder13.v:2.28-2.29" */
  input [1:0] A;
  wire [1:0] A;
  /* src = "adder13.v:2.31-2.32" */
  input [1:0] B;
  wire [1:0] B;
  /* src = "adder13.v:2.40-2.43" */
  input Cin;
  wire Cin;
  /* src = "adder13.v:2.78-2.82" */
  output Cout;
  wire Cout;
  /* src = "adder13.v:2.62-2.65" */
  output [1:0] Sum;
  wire [1:0] Sum;
  NOT _22_ (
    .A(Cin),
    .Y(_21_)
  );
  NOT _23_ (
    .A(A[0]),
    .Y(_00_)
  );
  NOT _24_ (
    .A(B[0]),
    .Y(_01_)
  );
  AND _25_ (
    .A(A[0]),
    .B(B[0]),
    .Y(_02_)
  );
  OR _26_ (
    .A(_00_),
    .B(_01_),
    .Y(_03_)
  );
  OR _27_ (
    .A(A[0]),
    .B(B[0]),
    .Y(_04_)
  );
  NOT _28_ (
    .A(_04_),
    .Y(_05_)
  );
  AND _29_ (
    .A(_03_),
    .B(_04_),
    .Y(_06_)
  );
  OR _30_ (
    .A(_02_),
    .B(_05_),
    .Y(_07_)
  );
  AND _31_ (
    .A(Cin),
    .B(_06_),
    .Y(_08_)
  );
  OR _32_ (
    .A(_21_),
    .B(_07_),
    .Y(_09_)
  );
  AND _33_ (
    .A(_03_),
    .B(_09_),
    .Y(_10_)
  );
  OR _34_ (
    .A(_02_),
    .B(_08_),
    .Y(_11_)
  );
  AND _35_ (
    .A(A[1]),
    .B(B[1]),
    .Y(_12_)
  );
  NOT _36_ (
    .A(_12_),
    .Y(_13_)
  );
  OR _37_ (
    .A(_11_),
    .B(_12_),
    .Y(Cout)
  );
  OR _38_ (
    .A(Cin),
    .B(_06_),
    .Y(_14_)
  );
  AND _39_ (
    .A(_09_),
    .B(_14_),
    .Y(Sum[0])
  );
  OR _40_ (
    .A(A[1]),
    .B(B[1]),
    .Y(_15_)
  );
  NOT _41_ (
    .A(_15_),
    .Y(_16_)
  );
  AND _42_ (
    .A(_13_),
    .B(_15_),
    .Y(_17_)
  );
  OR _43_ (
    .A(_12_),
    .B(_16_),
    .Y(_18_)
  );
  OR _44_ (
    .A(_11_),
    .B(_17_),
    .Y(_19_)
  );
  OR _45_ (
    .A(_10_),
    .B(_18_),
    .Y(_20_)
  );
  AND _46_ (
    .A(_19_),
    .B(_20_),
    .Y(Sum[1])
  );
endmodule
