/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "adder6.v:2.1-14.10" */
module adder6(A, B, Cin, Sum, Cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  /* src = "adder6.v:3.11-3.12" */
  input A;
  wire A;
  /* src = "adder6.v:3.13-3.14" */
  input B;
  wire B;
  /* src = "adder6.v:3.15-3.18" */
  input Cin;
  wire Cin;
  /* src = "adder6.v:4.16-4.20" */
  output Cout;
  wire Cout;
  /* src = "adder6.v:4.12-4.15" */
  output Sum;
  wire Sum;
  OR _10_ (
    .A(_07_),
    .B(_03_),
    .Y(Cout)
  );
  NOT _11_ (
    .A(Cin),
    .Y(_06_)
  );
  AND _12_ (
    .A(A),
    .B(B),
    .Y(_07_)
  );
  NOT _13_ (
    .A(_07_),
    .Y(_08_)
  );
  OR _14_ (
    .A(A),
    .B(B),
    .Y(_09_)
  );
  NOT _15_ (
    .A(_09_),
    .Y(_00_)
  );
  AND _16_ (
    .A(_08_),
    .B(_09_),
    .Y(_01_)
  );
  OR _17_ (
    .A(_07_),
    .B(_00_),
    .Y(_02_)
  );
  AND _18_ (
    .A(Cin),
    .B(_01_),
    .Y(_03_)
  );
  OR _19_ (
    .A(_06_),
    .B(_02_),
    .Y(_04_)
  );
  OR _20_ (
    .A(Cin),
    .B(_01_),
    .Y(_05_)
  );
  AND _21_ (
    .A(_04_),
    .B(_05_),
    .Y(Sum)
  );
endmodule
