/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "adder4.v:2.1-19.10" */
module adder4(A, B, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  /* src = "adder4.v:4.8-4.9" */
  input A;
  wire A;
  /* src = "adder4.v:4.10-4.11" */
  input B;
  wire B;
  /* src = "adder4.v:4.12-4.15" */
  input cin;
  wire cin;
  /* src = "adder4.v:5.13-5.17" */
  output cout;
  wire cout;
  /* src = "adder4.v:5.9-5.12" */
  output sum;
  wire sum;
  AND _07_ (
    .A(_00_),
    .B(_01_),
    .Y(_03_)
  );
  OR _08_ (
    .A(_02_),
    .B(_03_),
    .Y(sum)
  );
  OR _09_ (
    .A(B),
    .B(cin),
    .Y(_04_)
  );
  AND _10_ (
    .A(B),
    .B(cin),
    .Y(_05_)
  );
  AND _11_ (
    .A(A),
    .B(_04_),
    .Y(_06_)
  );
  OR _12_ (
    .A(_05_),
    .B(_06_),
    .Y(cout)
  );
  not _13_ (
    .A(cout),
    .Y(_00_)
  );
  OR _14_ (
    .A(A),
    .B(_04_),
    .Y(_01_)
  );
  AND _15_ (
    .A(A),
    .B(_05_),
    .Y(_02_)
  );
endmodule
