/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "adder15.v:2.1-17.10" */
module adder15(A, B, sum, carry_out);
  wire _0_;
  wire _1_;
  /* src = "adder15.v:4.13-4.14" */
  input A;
  wire A;
  /* src = "adder15.v:5.13-5.14" */
  input B;
  wire B;
  /* src = "adder15.v:7.13-7.22" */
  output carry_out;
  wire carry_out;
  /* src = "adder15.v:6.13-6.16" */
  output sum;
  wire sum;
  AND _2_ (
    .A(A),
    .B(B),
    .Y(carry_out)
  );
  not _3_ (
    .A(carry_out),
    .Y(_0_)
  );
  OR _4_ (
    .A(A),
    .B(B),
    .Y(_1_)
  );
  AND _5_ (
    .A(_0_),
    .B(_1_),
    .Y(sum)
  );
endmodule
