/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "adder3.v:2.1-16.10" */
module adder3(A, B, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  /* src = "adder3.v:4.8-4.9" */
  input A;
  wire A;
  /* src = "adder3.v:4.10-4.11" */
  input B;
  wire B;
  /* src = "adder3.v:4.12-4.15" */
  input cin;
  wire cin;
  /* src = "adder3.v:5.13-5.17" */
  output cout;
  wire cout;
  /* src = "adder3.v:5.9-5.12" */
  output sum;
  wire sum;
  NOT _10_ (
    .A(cin),
    .Y(_06_)
  );
  AND _11_ (
    .A(B),
    .B(A),
    .Y(_07_)
  );
  NOT _12_ (
    .A(_07_),
    .Y(_08_)
  );
  OR _13_ (
    .A(B),
    .B(A),
    .Y(_09_)
  );
  NOT _14_ (
    .A(_09_),
    .Y(_00_)
  );
  AND _15_ (
    .A(_08_),
    .B(_09_),
    .Y(_01_)
  );
  OR _16_ (
    .A(_07_),
    .B(_00_),
    .Y(_02_)
  );
  AND _17_ (
    .A(cin),
    .B(_01_),
    .Y(_03_)
  );
  OR _18_ (
    .A(_06_),
    .B(_02_),
    .Y(_04_)
  );
  OR _19_ (
    .A(_07_),
    .B(_03_),
    .Y(cout)
  );
  OR _20_ (
    .A(cin),
    .B(_01_),
    .Y(_05_)
  );
  AND _21_ (
    .A(_04_),
    .B(_05_),
    .Y(sum)
  );
endmodule
