/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "and16.v:2.1-12.10" */
module and16(a, b, out);
  /* src = "and16.v:3.16-3.17" */
  input a;
  wire a;
  /* src = "and16.v:4.16-4.17" */
  input b;
  wire b;
  /* src = "and16.v:5.16-5.19" */
  output out;
  wire out;
  AND _0_ (
    .A(a),
    .B(b),
    .Y(out)
  );
endmodule
