/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "and17.v:2.1-19.10" */
module and17(a, b, out);
  /* src = "and17.v:3.22-3.23" */
  input [7:0] a;
  wire [7:0] a;
  /* src = "and17.v:4.22-4.23" */
  input [7:0] b;
  wire [7:0] b;
  /* src = "and17.v:5.22-5.25" */
  output [7:0] out;
  wire [7:0] out;
  AND _0_ (
    .A(a[3]),
    .B(b[3]),
    .Y(out[3])
  );
  AND _1_ (
    .A(a[2]),
    .B(b[2]),
    .Y(out[2])
  );
  AND _2_ (
    .A(a[1]),
    .B(b[1]),
    .Y(out[1])
  );
  AND _3_ (
    .A(a[0]),
    .B(b[0]),
    .Y(out[0])
  );
  AND _4_ (
    .A(a[7]),
    .B(b[7]),
    .Y(out[7])
  );
  AND _5_ (
    .A(a[6]),
    .B(b[6]),
    .Y(out[6])
  );
  AND _6_ (
    .A(a[5]),
    .B(b[5]),
    .Y(out[5])
  );
  AND _7_ (
    .A(a[4]),
    .B(b[4]),
    .Y(out[4])
  );
endmodule
