/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "and2_gate.v:2.1-11.10" */
module and2_gate(a, b, out);
  /* src = "and2_gate.v:3.11-3.12" */
  input a;
  wire a;
  /* src = "and2_gate.v:3.13-3.14" */
  input b;
  wire b;
  /* src = "and2_gate.v:4.16-4.19" */
  output out;
  wire out;
  AND _0_ (
    .A(a),
    .B(b),
    .Y(out)
  );
endmodule
