/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "comparator9.v:1.1-17.10" */
module comparator9(A, B, A_less_B, A_equal_B, A_greater_B);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  /* src = "comparator9.v:1.33-1.34" */
  input [1:0] A;
  wire [1:0] A;
  /* src = "comparator9.v:1.55-1.64" */
  output A_equal_B;
  wire A_equal_B;
  /* src = "comparator9.v:1.66-1.77" */
  output A_greater_B;
  wire A_greater_B;
  /* src = "comparator9.v:1.45-1.53" */
  output A_less_B;
  wire A_less_B;
  /* src = "comparator9.v:1.35-1.36" */
  input [1:0] B;
  wire [1:0] B;
  not _16_ (
    .A(A[1]),
    .Y(_14_)
  );
  not _17_ (
    .A(A[0]),
    .Y(_15_)
  );
  not _18_ (
    .A(B[1]),
    .Y(_00_)
  );
  not _19_ (
    .A(B[0]),
    .Y(_01_)
  );
  AND _20_ (
    .A(_14_),
    .B(B[1]),
    .Y(_02_)
  );
  OR _21_ (
    .A(A[1]),
    .B(_00_),
    .Y(_03_)
  );
  AND _22_ (
    .A(_15_),
    .B(B[0]),
    .Y(_04_)
  );
  OR _23_ (
    .A(A[0]),
    .B(_01_),
    .Y(_05_)
  );
  AND _24_ (
    .A(_03_),
    .B(_05_),
    .Y(_06_)
  );
  OR _25_ (
    .A(_02_),
    .B(_04_),
    .Y(_07_)
  );
  AND _26_ (
    .A(A[1]),
    .B(_00_),
    .Y(_08_)
  );
  OR _27_ (
    .A(_14_),
    .B(B[1]),
    .Y(_09_)
  );
  AND _28_ (
    .A(A[0]),
    .B(_01_),
    .Y(_10_)
  );
  OR _29_ (
    .A(_15_),
    .B(B[0]),
    .Y(_11_)
  );
  AND _30_ (
    .A(_09_),
    .B(_11_),
    .Y(_12_)
  );
  OR _31_ (
    .A(_08_),
    .B(_10_),
    .Y(_13_)
  );
  AND _32_ (
    .A(_06_),
    .B(_12_),
    .Y(A_equal_B)
  );
  AND _33_ (
    .A(_07_),
    .B(_09_),
    .Y(A_less_B)
  );
  AND _34_ (
    .A(_03_),
    .B(_13_),
    .Y(A_greater_B)
  );
endmodule
