/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "comparator22.v:1.1-13.10" */
module comparator22(a, b, eq, gt, lt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  /* src = "comparator22.v:1.28-1.29" */
  input a;
  wire a;
  /* src = "comparator22.v:1.37-1.38" */
  input b;
  wire b;
  /* src = "comparator22.v:1.47-1.49" */
  output eq;
  wire eq;
  /* src = "comparator22.v:1.58-1.60" */
  output gt;
  wire gt;
  /* src = "comparator22.v:1.69-1.71" */
  output lt;
  wire lt;
  NOT _04_ (
    .A(a),
    .Y(_01_)
  );
  NOT _05_ (
    .A(b),
    .Y(_02_)
  );
  OR _06_ (
    .A(_01_),
    .B(b),
    .Y(_03_)
  );
  NOT _07_ (
    .A(_03_),
    .Y(gt)
  );
  OR _08_ (
    .A(a),
    .B(_02_),
    .Y(_00_)
  );
  NOT _09_ (
    .A(_00_),
    .Y(lt)
  );
  AND _10_ (
    .A(_03_),
    .B(_00_),
    .Y(eq)
  );
endmodule
