/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "comparator10.v:1.1-23.10" */
module comparator10(A, B, A_less_B, A_equal_B, A_greater_B);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  /* src = "comparator10.v:1.34-1.35" */
  input [1:0] A;
  wire [1:0] A;
  /* src = "comparator10.v:1.60-1.69" */
  output A_equal_B;
  wire A_equal_B;
  /* src = "comparator10.v:1.71-1.82" */
  output A_greater_B;
  wire A_greater_B;
  /* src = "comparator10.v:1.50-1.58" */
  output A_less_B;
  wire A_less_B;
  /* src = "comparator10.v:1.36-1.37" */
  input [1:0] B;
  wire [1:0] B;
  NOT _16_ (
    .A(A[0]),
    .Y(_14_)
  );
  NOT _17_ (
    .A(B[1]),
    .Y(_15_)
  );
  NOT _18_ (
    .A(A[1]),
    .Y(_00_)
  );
  NOT _19_ (
    .A(B[0]),
    .Y(_01_)
  );
  AND _20_ (
    .A(_15_),
    .B(A[1]),
    .Y(_02_)
  );
  OR _21_ (
    .A(B[1]),
    .B(_00_),
    .Y(_03_)
  );
  AND _22_ (
    .A(_14_),
    .B(B[0]),
    .Y(_04_)
  );
  OR _23_ (
    .A(A[0]),
    .B(_01_),
    .Y(_05_)
  );
  AND _24_ (
    .A(B[1]),
    .B(_00_),
    .Y(_06_)
  );
  OR _25_ (
    .A(_15_),
    .B(A[1]),
    .Y(_07_)
  );
  AND _26_ (
    .A(_05_),
    .B(_07_),
    .Y(_08_)
  );
  OR _27_ (
    .A(_04_),
    .B(_06_),
    .Y(_09_)
  );
  AND _28_ (
    .A(_03_),
    .B(_09_),
    .Y(A_less_B)
  );
  AND _29_ (
    .A(A[0]),
    .B(_01_),
    .Y(_10_)
  );
  OR _30_ (
    .A(_14_),
    .B(B[0]),
    .Y(_11_)
  );
  AND _31_ (
    .A(_03_),
    .B(_11_),
    .Y(_12_)
  );
  OR _32_ (
    .A(_02_),
    .B(_10_),
    .Y(_13_)
  );
  AND _33_ (
    .A(_08_),
    .B(_12_),
    .Y(A_equal_B)
  );
  AND _34_ (
    .A(_07_),
    .B(_13_),
    .Y(A_greater_B)
  );
endmodule
