/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder6.v:1.1-19.10" */
module decoder6(D, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "decoder6.v:2.13-2.14" */
  input [2:0] D;
  wire [2:0] D;
  /* src = "decoder6.v:3.18-3.19" */
  output [7:0] y;
  wire [7:0] y;
  not _09_ (
    .A(D[0]),
    .Y(_00_)
  );
  not _10_ (
    .A(D[1]),
    .Y(_01_)
  );
  not _11_ (
    .A(D[2]),
    .Y(_02_)
  );
  AND _12_ (
    .A(D[0]),
    .B(_01_),
    .Y(_03_)
  );
  AND _13_ (
    .A(_02_),
    .B(_03_),
    .Y(y[1])
  );
  AND _14_ (
    .A(_00_),
    .B(D[1]),
    .Y(_04_)
  );
  AND _15_ (
    .A(_02_),
    .B(_04_),
    .Y(y[2])
  );
  AND _16_ (
    .A(D[0]),
    .B(D[1]),
    .Y(_05_)
  );
  AND _17_ (
    .A(_02_),
    .B(_05_),
    .Y(y[3])
  );
  OR _18_ (
    .A(D[0]),
    .B(D[1]),
    .Y(_06_)
  );
  not _19_ (
    .A(_06_),
    .Y(_07_)
  );
  AND _20_ (
    .A(D[2]),
    .B(_07_),
    .Y(y[4])
  );
  AND _21_ (
    .A(D[2]),
    .B(_03_),
    .Y(y[5])
  );
  AND _22_ (
    .A(D[2]),
    .B(_04_),
    .Y(y[6])
  );
  AND _23_ (
    .A(D[2]),
    .B(_05_),
    .Y(y[7])
  );
  OR _24_ (
    .A(D[2]),
    .B(_06_),
    .Y(_08_)
  );
  not _25_ (
    .A(_08_),
    .Y(y[0])
  );
endmodule
