/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder8.v:1.1-42.10" */
module decoder8(ip0, ip1, ip2, op0, op1, op2, op3, op4, op5, op6, op7);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "decoder8.v:3.7-3.10" */
  input ip0;
  wire ip0;
  /* src = "decoder8.v:3.11-3.14" */
  input ip1;
  wire ip1;
  /* src = "decoder8.v:3.15-3.18" */
  input ip2;
  wire ip2;
  /* src = "decoder8.v:4.12-4.15" */
  output op0;
  wire op0;
  /* src = "decoder8.v:4.16-4.19" */
  output op1;
  wire op1;
  /* src = "decoder8.v:4.20-4.23" */
  output op2;
  wire op2;
  /* src = "decoder8.v:4.24-4.27" */
  output op3;
  wire op3;
  /* src = "decoder8.v:4.28-4.31" */
  output op4;
  wire op4;
  /* src = "decoder8.v:4.32-4.35" */
  output op5;
  wire op5;
  /* src = "decoder8.v:4.36-4.39" */
  output op6;
  wire op6;
  /* src = "decoder8.v:4.40-4.43" */
  output op7;
  wire op7;
  NOT _09_ (
    .A(ip0),
    .Y(_00_)
  );
  NOT _10_ (
    .A(ip1),
    .Y(_01_)
  );
  NOT _11_ (
    .A(ip2),
    .Y(_02_)
  );
  OR _12_ (
    .A(ip0),
    .B(ip1),
    .Y(_03_)
  );
  NOT _13_ (
    .A(_03_),
    .Y(_04_)
  );
  OR _14_ (
    .A(ip2),
    .B(_03_),
    .Y(_05_)
  );
  NOT _15_ (
    .A(_05_),
    .Y(op0)
  );
  AND _16_ (
    .A(ip0),
    .B(ip1),
    .Y(_06_)
  );
  AND _17_ (
    .A(ip2),
    .B(_06_),
    .Y(op7)
  );
  AND _18_ (
    .A(_00_),
    .B(ip1),
    .Y(_07_)
  );
  AND _19_ (
    .A(ip2),
    .B(_07_),
    .Y(op6)
  );
  AND _20_ (
    .A(ip0),
    .B(_01_),
    .Y(_08_)
  );
  AND _21_ (
    .A(ip2),
    .B(_08_),
    .Y(op5)
  );
  AND _22_ (
    .A(ip2),
    .B(_04_),
    .Y(op4)
  );
  AND _23_ (
    .A(_02_),
    .B(_06_),
    .Y(op3)
  );
  AND _24_ (
    .A(_02_),
    .B(_07_),
    .Y(op2)
  );
  AND _25_ (
    .A(_02_),
    .B(_08_),
    .Y(op1)
  );
endmodule
