/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder22.v:1.1-12.10" */
module decoder22(a, b, c, en, d0, d1, d2, d3, d4, d5, d6, d7);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "decoder22.v:2.7-2.8" */
  input a;
  wire a;
  /* src = "decoder22.v:2.9-2.10" */
  input b;
  wire b;
  /* src = "decoder22.v:2.11-2.12" */
  input c;
  wire c;
  /* src = "decoder22.v:3.8-3.10" */
  output d0;
  wire d0;
  /* src = "decoder22.v:3.11-3.13" */
  output d1;
  wire d1;
  /* src = "decoder22.v:3.14-3.16" */
  output d2;
  wire d2;
  /* src = "decoder22.v:3.17-3.19" */
  output d3;
  wire d3;
  /* src = "decoder22.v:3.20-3.22" */
  output d4;
  wire d4;
  /* src = "decoder22.v:3.23-3.25" */
  output d5;
  wire d5;
  /* src = "decoder22.v:3.26-3.28" */
  output d6;
  wire d6;
  /* src = "decoder22.v:3.29-3.31" */
  output d7;
  wire d7;
  /* src = "decoder22.v:2.13-2.15" */
  input en;
  wire en;
  not _09_ (
    .A(a),
    .Y(_00_)
  );
  not _10_ (
    .A(b),
    .Y(_01_)
  );
  not _11_ (
    .A(c),
    .Y(_02_)
  );
  AND _12_ (
    .A(_00_),
    .B(en),
    .Y(_03_)
  );
  AND _13_ (
    .A(_01_),
    .B(_03_),
    .Y(_04_)
  );
  AND _14_ (
    .A(_02_),
    .B(_04_),
    .Y(d0)
  );
  AND _15_ (
    .A(c),
    .B(_04_),
    .Y(d1)
  );
  AND _16_ (
    .A(b),
    .B(_03_),
    .Y(_05_)
  );
  AND _17_ (
    .A(_02_),
    .B(_05_),
    .Y(d2)
  );
  AND _18_ (
    .A(c),
    .B(_05_),
    .Y(d3)
  );
  AND _19_ (
    .A(a),
    .B(en),
    .Y(_06_)
  );
  AND _20_ (
    .A(_01_),
    .B(_06_),
    .Y(_07_)
  );
  AND _21_ (
    .A(_02_),
    .B(_07_),
    .Y(d4)
  );
  AND _22_ (
    .A(c),
    .B(_07_),
    .Y(d5)
  );
  AND _23_ (
    .A(b),
    .B(_06_),
    .Y(_08_)
  );
  AND _24_ (
    .A(_02_),
    .B(_08_),
    .Y(d6)
  );
  AND _25_ (
    .A(c),
    .B(_08_),
    .Y(d7)
  );
endmodule
