/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder17.v:1.1-18.10" */
module decoder17(a, b, c, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "decoder17.v:2.7-2.8" */
  input a;
  wire a;
  /* src = "decoder17.v:2.9-2.10" */
  input b;
  wire b;
  /* src = "decoder17.v:2.11-2.12" */
  input c;
  wire c;
  /* src = "decoder17.v:3.18-3.21" */
  output [7:0] out;
  wire [7:0] out;
  NOT _09_ (
    .A(b),
    .Y(_00_)
  );
  NOT _10_ (
    .A(c),
    .Y(_01_)
  );
  NOT _11_ (
    .A(a),
    .Y(_02_)
  );
  OR _12_ (
    .A(b),
    .B(c),
    .Y(_03_)
  );
  NOT _13_ (
    .A(_03_),
    .Y(_04_)
  );
  OR _14_ (
    .A(a),
    .B(_03_),
    .Y(_05_)
  );
  NOT _15_ (
    .A(_05_),
    .Y(out[0])
  );
  AND _16_ (
    .A(_00_),
    .B(c),
    .Y(_06_)
  );
  AND _17_ (
    .A(_02_),
    .B(_06_),
    .Y(out[1])
  );
  AND _18_ (
    .A(b),
    .B(_01_),
    .Y(_07_)
  );
  AND _19_ (
    .A(_02_),
    .B(_07_),
    .Y(out[2])
  );
  AND _20_ (
    .A(b),
    .B(c),
    .Y(_08_)
  );
  AND _21_ (
    .A(_02_),
    .B(_08_),
    .Y(out[3])
  );
  AND _22_ (
    .A(a),
    .B(_04_),
    .Y(out[4])
  );
  AND _23_ (
    .A(a),
    .B(_06_),
    .Y(out[5])
  );
  AND _24_ (
    .A(a),
    .B(_07_),
    .Y(out[6])
  );
  AND _25_ (
    .A(a),
    .B(_08_),
    .Y(out[7])
  );
endmodule
