/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder23.v:1.1-16.10" */
module decoder23(in, en, out1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "decoder23.v:3.7-3.9" */
  input en;
  wire en;
  /* src = "decoder23.v:2.13-2.15" */
  input [2:0] in;
  wire [2:0] in;
  /* src = "decoder23.v:4.14-4.18" */
  output [7:0] out1;
  wire [7:0] out1;
  NOT _09_ (
    .A(in[2]),
    .Y(_00_)
  );
  NOT _10_ (
    .A(in[1]),
    .Y(_01_)
  );
  NOT _11_ (
    .A(in[0]),
    .Y(_02_)
  );
  AND _12_ (
    .A(_00_),
    .B(en),
    .Y(_03_)
  );
  AND _13_ (
    .A(_01_),
    .B(_03_),
    .Y(_04_)
  );
  AND _14_ (
    .A(_02_),
    .B(_04_),
    .Y(out1[0])
  );
  AND _15_ (
    .A(in[0]),
    .B(_04_),
    .Y(out1[1])
  );
  AND _16_ (
    .A(in[1]),
    .B(_03_),
    .Y(_05_)
  );
  AND _17_ (
    .A(_02_),
    .B(_05_),
    .Y(out1[2])
  );
  AND _18_ (
    .A(in[0]),
    .B(_05_),
    .Y(out1[3])
  );
  AND _19_ (
    .A(in[2]),
    .B(en),
    .Y(_06_)
  );
  AND _20_ (
    .A(_01_),
    .B(_06_),
    .Y(_07_)
  );
  AND _21_ (
    .A(_02_),
    .B(_07_),
    .Y(out1[4])
  );
  AND _22_ (
    .A(in[0]),
    .B(_07_),
    .Y(out1[5])
  );
  AND _23_ (
    .A(in[1]),
    .B(_06_),
    .Y(_08_)
  );
  AND _24_ (
    .A(_02_),
    .B(_08_),
    .Y(out1[6])
  );
  AND _25_ (
    .A(in[0]),
    .B(_08_),
    .Y(out1[7])
  );
endmodule
