/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder4.v:1.1-21.10" */
module decoder4(en, a, b, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  /* src = "decoder4.v:3.14-3.15" */
  input a;
  wire a;
  /* src = "decoder4.v:3.16-3.17" */
  input b;
  wire b;
  /* src = "decoder4.v:3.11-3.13" */
  input en;
  wire en;
  /* src = "decoder4.v:4.17-4.18" */
  output [3:0] y;
  wire [3:0] y;
  NOT _04_ (
    .A(a),
    .Y(_02_)
  );
  NOT _05_ (
    .A(b),
    .Y(_03_)
  );
  OR _06_ (
    .A(en),
    .B(_02_),
    .Y(_00_)
  );
  OR _07_ (
    .A(_03_),
    .B(_00_),
    .Y(y[3])
  );
  OR _08_ (
    .A(en),
    .B(a),
    .Y(_01_)
  );
  OR _09_ (
    .A(b),
    .B(_01_),
    .Y(y[0])
  );
  OR _10_ (
    .A(_03_),
    .B(_01_),
    .Y(y[1])
  );
  OR _11_ (
    .A(b),
    .B(_00_),
    .Y(y[2])
  );
endmodule
