/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder9.v:1.1-30.10" */
module decoder9(ip0, ip1, en, op0, op1, op2, op3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  /* src = "decoder9.v:3.15-3.17" */
  input en;
  wire en;
  /* src = "decoder9.v:3.7-3.10" */
  input ip0;
  wire ip0;
  /* src = "decoder9.v:3.11-3.14" */
  input ip1;
  wire ip1;
  /* src = "decoder9.v:4.12-4.15" */
  output op0;
  wire op0;
  /* src = "decoder9.v:4.16-4.19" */
  output op1;
  wire op1;
  /* src = "decoder9.v:4.20-4.23" */
  output op2;
  wire op2;
  /* src = "decoder9.v:4.24-4.27" */
  output op3;
  wire op3;
  NOT _04_ (
    .A(ip1),
    .Y(_02_)
  );
  NOT _05_ (
    .A(ip0),
    .Y(_03_)
  );
  AND _06_ (
    .A(_03_),
    .B(en),
    .Y(_00_)
  );
  AND _07_ (
    .A(_02_),
    .B(_00_),
    .Y(op0)
  );
  AND _08_ (
    .A(ip0),
    .B(en),
    .Y(_01_)
  );
  AND _09_ (
    .A(ip1),
    .B(_01_),
    .Y(op3)
  );
  AND _10_ (
    .A(ip1),
    .B(_00_),
    .Y(op2)
  );
  AND _11_ (
    .A(_02_),
    .B(_01_),
    .Y(op1)
  );
endmodule
