/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder1.v:2.1-21.10" */
module decoder1(in, out);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "decoder1.v:4.14-4.16" */
  input [1:0] in;
  wire [1:0] in;
  /* src = "decoder1.v:5.19-5.22" */
  output [3:0] out;
  wire [3:0] out;
  NOT _3_ (
    .A(in[1]),
    .Y(_1_)
  );
  NOT _4_ (
    .A(in[0]),
    .Y(_2_)
  );
  AND _5_ (
    .A(in[1]),
    .B(in[0]),
    .Y(out[0])
  );
  AND _6_ (
    .A(in[1]),
    .B(_2_),
    .Y(out[1])
  );
  AND _7_ (
    .A(_1_),
    .B(in[0]),
    .Y(out[2])
  );
  OR _8_ (
    .A(in[1]),
    .B(in[0]),
    .Y(_0_)
  );
  NOT _9_ (
    .A(_0_),
    .Y(out[3])
  );
endmodule
