/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder20.v:1.1-10.10" */
module decoder20(in, out3);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "decoder20.v:4.17-4.19" */
  input [1:0] in;
  wire [1:0] in;
  /* src = "decoder20.v:3.22-3.26" */
  output [7:0] out3;
  wire [7:0] out3;
  NOT _3_ (
    .A(in[1]),
    .Y(_0_)
  );
  NOT _4_ (
    .A(in[0]),
    .Y(_1_)
  );
  OR _5_ (
    .A(in[1]),
    .B(in[0]),
    .Y(_2_)
  );
  NOT _6_ (
    .A(_2_),
    .Y(out3[0])
  );
  AND _7_ (
    .A(_0_),
    .B(in[0]),
    .Y(out3[1])
  );
  AND _8_ (
    .A(in[1]),
    .B(_1_),
    .Y(out3[2])
  );
  AND _9_ (
    .A(in[1]),
    .B(in[0]),
    .Y(out3[3])
  );
  assign out3[7:4] = 4'h0;
endmodule
