/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder14.v:1.1-28.10" */
module decoder14(Data_in, Data_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "decoder14.v:7.17-7.24" */
  input [2:0] Data_in;
  wire [2:0] Data_in;
  /* src = "decoder14.v:9.18-9.26" */
  output [7:0] Data_out;
  wire [7:0] Data_out;
  NOT _09_ (
    .A(Data_in[1]),
    .Y(_00_)
  );
  NOT _10_ (
    .A(Data_in[0]),
    .Y(_01_)
  );
  NOT _11_ (
    .A(Data_in[2]),
    .Y(_02_)
  );
  OR _12_ (
    .A(Data_in[1]),
    .B(Data_in[0]),
    .Y(_03_)
  );
  NOT _13_ (
    .A(_03_),
    .Y(_04_)
  );
  OR _14_ (
    .A(Data_in[2]),
    .B(_03_),
    .Y(_05_)
  );
  NOT _15_ (
    .A(_05_),
    .Y(Data_out[0])
  );
  AND _16_ (
    .A(_00_),
    .B(Data_in[0]),
    .Y(_06_)
  );
  AND _17_ (
    .A(_02_),
    .B(_06_),
    .Y(Data_out[1])
  );
  AND _18_ (
    .A(Data_in[1]),
    .B(_01_),
    .Y(_07_)
  );
  AND _19_ (
    .A(_02_),
    .B(_07_),
    .Y(Data_out[2])
  );
  AND _20_ (
    .A(Data_in[1]),
    .B(Data_in[0]),
    .Y(_08_)
  );
  AND _21_ (
    .A(_02_),
    .B(_08_),
    .Y(Data_out[3])
  );
  AND _22_ (
    .A(Data_in[2]),
    .B(_04_),
    .Y(Data_out[4])
  );
  AND _23_ (
    .A(Data_in[2]),
    .B(_06_),
    .Y(Data_out[5])
  );
  AND _24_ (
    .A(Data_in[2]),
    .B(_07_),
    .Y(Data_out[6])
  );
  AND _25_ (
    .A(Data_in[2]),
    .B(_08_),
    .Y(Data_out[7])
  );
endmodule
