/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder29.v:1.1-21.10" */
module decoder29(x, y, z, w, d);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  /* src = "decoder29.v:3.14-3.15" */
  output [15:0] d;
  wire [15:0] d;
  /* src = "decoder29.v:2.8-2.9" */
  input w;
  wire w;
  /* src = "decoder29.v:2.10-2.11" */
  input x;
  wire x;
  /* src = "decoder29.v:2.12-2.13" */
  input y;
  wire y;
  /* src = "decoder29.v:2.14-2.15" */
  input z;
  wire z;
  NOT _19_ (
    .A(x),
    .Y(_00_)
  );
  NOT _20_ (
    .A(y),
    .Y(_01_)
  );
  NOT _21_ (
    .A(z),
    .Y(_02_)
  );
  NOT _22_ (
    .A(w),
    .Y(_03_)
  );
  OR _23_ (
    .A(x),
    .B(y),
    .Y(_04_)
  );
  NOT _24_ (
    .A(_04_),
    .Y(_05_)
  );
  OR _25_ (
    .A(z),
    .B(_04_),
    .Y(_06_)
  );
  NOT _26_ (
    .A(_06_),
    .Y(_07_)
  );
  OR _27_ (
    .A(w),
    .B(_06_),
    .Y(_08_)
  );
  NOT _28_ (
    .A(_08_),
    .Y(d[0])
  );
  AND _29_ (
    .A(w),
    .B(_07_),
    .Y(d[1])
  );
  AND _30_ (
    .A(z),
    .B(_05_),
    .Y(_09_)
  );
  AND _31_ (
    .A(_03_),
    .B(_09_),
    .Y(d[2])
  );
  AND _32_ (
    .A(w),
    .B(_09_),
    .Y(d[3])
  );
  AND _33_ (
    .A(_00_),
    .B(y),
    .Y(_10_)
  );
  AND _34_ (
    .A(_02_),
    .B(_10_),
    .Y(_11_)
  );
  AND _35_ (
    .A(_03_),
    .B(_11_),
    .Y(d[4])
  );
  AND _36_ (
    .A(w),
    .B(_11_),
    .Y(d[5])
  );
  AND _37_ (
    .A(z),
    .B(_10_),
    .Y(_12_)
  );
  AND _38_ (
    .A(_03_),
    .B(_12_),
    .Y(d[6])
  );
  AND _39_ (
    .A(w),
    .B(_12_),
    .Y(d[7])
  );
  AND _40_ (
    .A(x),
    .B(_01_),
    .Y(_13_)
  );
  AND _41_ (
    .A(_02_),
    .B(_13_),
    .Y(_14_)
  );
  AND _42_ (
    .A(_03_),
    .B(_14_),
    .Y(d[8])
  );
  AND _43_ (
    .A(w),
    .B(_14_),
    .Y(d[9])
  );
  AND _44_ (
    .A(z),
    .B(_13_),
    .Y(_15_)
  );
  AND _45_ (
    .A(_03_),
    .B(_15_),
    .Y(d[10])
  );
  AND _46_ (
    .A(w),
    .B(_15_),
    .Y(d[11])
  );
  AND _47_ (
    .A(x),
    .B(y),
    .Y(_16_)
  );
  AND _48_ (
    .A(_02_),
    .B(_16_),
    .Y(_17_)
  );
  AND _49_ (
    .A(_03_),
    .B(_17_),
    .Y(d[12])
  );
  AND _50_ (
    .A(w),
    .B(_17_),
    .Y(d[13])
  );
  AND _51_ (
    .A(z),
    .B(_16_),
    .Y(_18_)
  );
  AND _52_ (
    .A(_03_),
    .B(_18_),
    .Y(d[14])
  );
  AND _53_ (
    .A(w),
    .B(_18_),
    .Y(d[15])
  );
endmodule
