/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder11.v:1.1-20.10" */
module decoder11(in, out);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "decoder11.v:3.14-3.16" */
  input [1:0] in;
  wire [1:0] in;
  /* src = "decoder11.v:4.19-4.22" */
  output [3:0] out;
  wire [3:0] out;
  NOT _3_ (
    .A(in[1]),
    .Y(_0_)
  );
  NOT _4_ (
    .A(in[0]),
    .Y(_1_)
  );
  OR _5_ (
    .A(in[1]),
    .B(in[0]),
    .Y(_2_)
  );
  NOT _6_ (
    .A(_2_),
    .Y(out[0])
  );
  AND _7_ (
    .A(_0_),
    .B(in[0]),
    .Y(out[1])
  );
  AND _8_ (
    .A(in[1]),
    .B(_1_),
    .Y(out[2])
  );
  AND _9_ (
    .A(in[1]),
    .B(in[0]),
    .Y(out[3])
  );
endmodule
