/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "encoder1.v:1.1-8.10" */
module encoder1(D, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  /* src = "encoder1.v:2.13-2.14" */
  input [7:0] D;
  wire [7:0] D;
  /* src = "encoder1.v:3.14-3.15" */
  output [2:0] y;
  wire [2:0] y;
  OR _05_ (
    .A(_00_),
    .B(_01_),
    .Y(y[2])
  );
  OR _06_ (
    .A(D[2]),
    .B(D[3]),
    .Y(_03_)
  );
  OR _07_ (
    .A(_02_),
    .B(_03_),
    .Y(y[1])
  );
  OR _08_ (
    .A(D[3]),
    .B(D[1]),
    .Y(_04_)
  );
  OR _09_ (
    .A(_00_),
    .B(_04_),
    .Y(y[0])
  );
  OR _10_ (
    .A(D[5]),
    .B(D[7]),
    .Y(_00_)
  );
  OR _11_ (
    .A(D[4]),
    .B(D[6]),
    .Y(_01_)
  );
  OR _12_ (
    .A(D[6]),
    .B(D[7]),
    .Y(_02_)
  );
endmodule
