/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "encoder12.v:1.1-9.10" */
module encoder12(y, a, en);
  wire _0_;
  wire _1_;
  /* src = "encoder12.v:4.18-4.19" */
  output [1:0] a;
  wire [1:0] a;
  /* src = "encoder12.v:3.11-3.13" */
  input en;
  wire en;
  /* src = "encoder12.v:2.17-2.18" */
  input [3:0] y;
  wire [3:0] y;
  OR _2_ (
    .A(y[3]),
    .B(y[1]),
    .Y(_0_)
  );
  AND _3_ (
    .A(en),
    .B(_0_),
    .Y(a[0])
  );
  OR _4_ (
    .A(y[3]),
    .B(y[2]),
    .Y(_1_)
  );
  AND _5_ (
    .A(en),
    .B(_1_),
    .Y(a[1])
  );
endmodule
