/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "encoder15.v:1.1-8.10" */
module encoder15(en, D, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  /* src = "encoder15.v:2.13-2.14" */
  input [7:0] D;
  wire [7:0] D;
  /* src = "encoder15.v:1.25-1.27" */
  input en;
  wire en;
  /* src = "encoder15.v:3.14-3.15" */
  output [2:0] y;
  wire [2:0] y;
  OR _08_ (
    .A(D[5]),
    .B(D[3]),
    .Y(_00_)
  );
  OR _09_ (
    .A(D[7]),
    .B(D[1]),
    .Y(_01_)
  );
  OR _10_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  AND _11_ (
    .A(en),
    .B(_02_),
    .Y(y[0])
  );
  OR _12_ (
    .A(D[7]),
    .B(D[6]),
    .Y(_03_)
  );
  OR _13_ (
    .A(D[4]),
    .B(D[5]),
    .Y(_04_)
  );
  OR _14_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  AND _15_ (
    .A(en),
    .B(_05_),
    .Y(y[2])
  );
  OR _16_ (
    .A(D[2]),
    .B(D[3]),
    .Y(_06_)
  );
  OR _17_ (
    .A(_03_),
    .B(_06_),
    .Y(_07_)
  );
  AND _18_ (
    .A(en),
    .B(_07_),
    .Y(y[1])
  );
endmodule
