/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "encoder11.v:1.1-8.10" */
module encoder11(y1, y2, y3, a0, a1, en);
  wire _0_;
  wire _1_;
  /* src = "encoder11.v:3.12-3.14" */
  output a0;
  wire a0;
  /* src = "encoder11.v:3.15-3.17" */
  output a1;
  wire a1;
  /* src = "encoder11.v:2.20-2.22" */
  input en;
  wire en;
  /* src = "encoder11.v:2.11-2.13" */
  input y1;
  wire y1;
  /* src = "encoder11.v:2.14-2.16" */
  input y2;
  wire y2;
  /* src = "encoder11.v:2.17-2.19" */
  input y3;
  wire y3;
  OR _2_ (
    .A(y3),
    .B(y1),
    .Y(_0_)
  );
  AND _3_ (
    .A(en),
    .B(_0_),
    .Y(a0)
  );
  OR _4_ (
    .A(y3),
    .B(y2),
    .Y(_1_)
  );
  AND _5_ (
    .A(en),
    .B(_1_),
    .Y(a1)
  );
endmodule
