/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "encoder8.v:1.1-8.10" */
module encoder8(y1, y2, y3, a0, a1);
  /* src = "encoder8.v:3.12-3.14" */
  output a0;
  wire a0;
  /* src = "encoder8.v:3.15-3.17" */
  output a1;
  wire a1;
  /* src = "encoder8.v:2.11-2.13" */
  input y1;
  wire y1;
  /* src = "encoder8.v:2.14-2.16" */
  input y2;
  wire y2;
  /* src = "encoder8.v:2.17-2.19" */
  input y3;
  wire y3;
  OR _0_ (
    .A(y3),
    .B(y1),
    .Y(a0)
  );
  OR _1_ (
    .A(y3),
    .B(y2),
    .Y(a1)
  );
endmodule
