/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mult13.v:1.1-44.10" */
module mult13(a, b, result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  /* src = "mult13.v:2.17-2.18" */
  input [1:0] a;
  wire [1:0] a;
  /* src = "mult13.v:3.17-3.18" */
  input [2:0] b;
  wire [2:0] b;
  /* src = "mult13.v:4.22-4.28" */
  output [4:0] result;
  wire [4:0] result;
  AND _19_ (
    .A(b[0]),
    .B(a[0]),
    .Y(result[0])
  );
  not _20_ (
    .A(result[0]),
    .Y(_00_)
  );
  AND _21_ (
    .A(a[0]),
    .B(b[1]),
    .Y(_01_)
  );
  AND _22_ (
    .A(b[0]),
    .B(a[1]),
    .Y(_02_)
  );
  OR _23_ (
    .A(_01_),
    .B(_02_),
    .Y(_03_)
  );
  AND _24_ (
    .A(_01_),
    .B(_02_),
    .Y(_04_)
  );
  not _25_ (
    .A(_04_),
    .Y(_05_)
  );
  AND _26_ (
    .A(_03_),
    .B(_05_),
    .Y(result[1])
  );
  AND _27_ (
    .A(a[0]),
    .B(b[2]),
    .Y(_06_)
  );
  not _28_ (
    .A(_06_),
    .Y(_07_)
  );
  AND _29_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_08_)
  );
  not _30_ (
    .A(_08_),
    .Y(_09_)
  );
  AND _31_ (
    .A(_00_),
    .B(_08_),
    .Y(_10_)
  );
  OR _32_ (
    .A(result[0]),
    .B(_09_),
    .Y(_11_)
  );
  OR _33_ (
    .A(_06_),
    .B(_10_),
    .Y(_12_)
  );
  OR _34_ (
    .A(_07_),
    .B(_11_),
    .Y(_13_)
  );
  AND _35_ (
    .A(_12_),
    .B(_13_),
    .Y(result[2])
  );
  AND _36_ (
    .A(b[1]),
    .B(result[0]),
    .Y(_14_)
  );
  OR _37_ (
    .A(b[2]),
    .B(_14_),
    .Y(_15_)
  );
  AND _38_ (
    .A(b[1]),
    .B(_06_),
    .Y(_16_)
  );
  not _39_ (
    .A(_16_),
    .Y(_17_)
  );
  AND _40_ (
    .A(a[1]),
    .B(_15_),
    .Y(_18_)
  );
  AND _41_ (
    .A(_17_),
    .B(_18_),
    .Y(result[3])
  );
  AND _42_ (
    .A(_06_),
    .B(_08_),
    .Y(result[4])
  );
endmodule
