/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mult9.v:1.1-13.10" */
module mult9(a, b, result);
  /* src = "mult9.v:1.21-1.22" */
  input a;
  wire a;
  /* src = "mult9.v:1.24-1.25" */
  input b;
  wire b;
  /* src = "mult9.v:2.24-2.30" */
  output result;
  wire result;
  AND _0_ (
    .A(a),
    .B(b),
    .Y(result)
  );
endmodule
