/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mult21.v:2.1-18.10" */
module mult21(a, b, c);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  /* src = "mult21.v:3.16-3.17" */
  input [1:0] a;
  wire [1:0] a;
  /* src = "mult21.v:3.19-3.20" */
  input [1:0] b;
  wire [1:0] b;
  /* src = "mult21.v:4.17-4.18" */
  output [3:0] c;
  wire [3:0] c;
  AND _06_ (
    .A(c[0]),
    .B(_03_),
    .Y(c[3])
  );
  NOT _07_ (
    .A(c[3]),
    .Y(_04_)
  );
  OR _08_ (
    .A(_01_),
    .B(_02_),
    .Y(_05_)
  );
  AND _09_ (
    .A(_04_),
    .B(_05_),
    .Y(c[1])
  );
  AND _10_ (
    .A(_00_),
    .B(_03_),
    .Y(c[2])
  );
  AND _11_ (
    .A(a[0]),
    .B(b[0]),
    .Y(c[0])
  );
  NOT _12_ (
    .A(c[0]),
    .Y(_00_)
  );
  AND _13_ (
    .A(b[0]),
    .B(a[1]),
    .Y(_01_)
  );
  AND _14_ (
    .A(a[0]),
    .B(b[1]),
    .Y(_02_)
  );
  AND _15_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_03_)
  );
endmodule
