/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mult4.v:2.1-13.10" */
module mult4(a1, a0, b1, b0, result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  /* src = "mult4.v:2.24-2.26" */
  input a0;
  wire a0;
  /* src = "mult4.v:2.21-2.23" */
  input a1;
  wire a1;
  /* src = "mult4.v:2.30-2.32" */
  input b0;
  wire b0;
  /* src = "mult4.v:2.27-2.29" */
  input b1;
  wire b1;
  /* src = "mult4.v:3.26-3.32" */
  output [3:0] result;
  wire [3:0] result;
  AND _06_ (
    .A(a0),
    .B(b1),
    .Y(_05_)
  );
  AND _07_ (
    .A(b0),
    .B(a1),
    .Y(_00_)
  );
  AND _08_ (
    .A(a0),
    .B(b0),
    .Y(result[0])
  );
  not _09_ (
    .A(result[0]),
    .Y(_01_)
  );
  AND _10_ (
    .A(a1),
    .B(b1),
    .Y(_02_)
  );
  AND _11_ (
    .A(result[0]),
    .B(_02_),
    .Y(result[3])
  );
  not _12_ (
    .A(result[3]),
    .Y(_03_)
  );
  OR _13_ (
    .A(_05_),
    .B(_00_),
    .Y(_04_)
  );
  AND _14_ (
    .A(_03_),
    .B(_04_),
    .Y(result[1])
  );
  AND _15_ (
    .A(_01_),
    .B(_02_),
    .Y(result[2])
  );
endmodule
