/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mult3.v:1.1-12.10" */
module mult3(a, b, result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  /* src = "mult3.v:1.27-1.28" */
  input [1:0] a;
  wire [1:0] a;
  /* src = "mult3.v:1.30-1.31" */
  input [1:0] b;
  wire [1:0] b;
  /* src = "mult3.v:2.26-2.32" */
  output [3:0] result;
  wire [3:0] result;
  AND _06_ (
    .A(a[0]),
    .B(b[1]),
    .Y(_05_)
  );
  AND _07_ (
    .A(b[0]),
    .B(a[1]),
    .Y(_00_)
  );
  AND _08_ (
    .A(a[0]),
    .B(b[0]),
    .Y(result[0])
  );
  not _09_ (
    .A(result[0]),
    .Y(_01_)
  );
  AND _10_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_02_)
  );
  AND _11_ (
    .A(result[0]),
    .B(_02_),
    .Y(result[3])
  );
  not _12_ (
    .A(result[3]),
    .Y(_03_)
  );
  OR _13_ (
    .A(_05_),
    .B(_00_),
    .Y(_04_)
  );
  AND _14_ (
    .A(_03_),
    .B(_04_),
    .Y(result[1])
  );
  AND _15_ (
    .A(_01_),
    .B(_02_),
    .Y(result[2])
  );
endmodule
