/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mux13.v:3.1-17.10" */
module mux13(in, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  /* src = "mux13.v:3.27-3.29" */
  input [3:0] in;
  wire [3:0] in;
  /* src = "mux13.v:4.41-4.44" */
  input [1:0] sel;
  wire [1:0] sel;
  /* src = "mux13.v:5.40-5.41" */
  output y;
  wire y;
  NOT _10_ (
    .A(sel[1]),
    .Y(_08_)
  );
  NOT _11_ (
    .A(sel[0]),
    .Y(_09_)
  );
  AND _12_ (
    .A(sel[0]),
    .B(in[3]),
    .Y(_00_)
  );
  AND _13_ (
    .A(_09_),
    .B(in[2]),
    .Y(_01_)
  );
  OR _14_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  AND _15_ (
    .A(sel[1]),
    .B(_02_),
    .Y(_03_)
  );
  AND _16_ (
    .A(sel[0]),
    .B(in[1]),
    .Y(_04_)
  );
  AND _17_ (
    .A(_09_),
    .B(in[0]),
    .Y(_05_)
  );
  OR _18_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  AND _19_ (
    .A(_08_),
    .B(_06_),
    .Y(_07_)
  );
  OR _20_ (
    .A(_03_),
    .B(_07_),
    .Y(y)
  );
endmodule
