/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mux14.v:2.1-14.10" */
module mux14(in, sel, y);
  /* src = "mux14.v:6.5-11.8" */
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  /* src = "mux14.v:2.27-2.29" */
  input [1:0] in;
  wire [1:0] in;
  /* src = "mux14.v:3.41-3.44" */
  input [1:0] sel;
  wire [1:0] sel;
  /* src = "mux14.v:4.40-4.41" */
  output y;
  reg y;
  NOT _08_ (
    .A(sel[0]),
    .Y(_05_)
  );
  NOT _09_ (
    .A(sel[1]),
    .Y(_06_)
  );
  AND _10_ (
    .A(sel[0]),
    .B(_06_),
    .Y(_07_)
  );
  OR _11_ (
    .A(_05_),
    .B(sel[1]),
    .Y(_02_)
  );
  AND _12_ (
    .A(in[1]),
    .B(_07_),
    .Y(_03_)
  );
  AND _13_ (
    .A(in[0]),
    .B(_02_),
    .Y(_04_)
  );
  OR _14_ (
    .A(_03_),
    .B(_04_),
    .Y(_00_)
  );
  WIRE _15_ (
    .A(sel[1]),
    .Z(_01_)
  );
  /* src = "mux14.v:6.5-11.8" */
  always @*
    if (!_01_) y = _00_;
endmodule
