/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mux3.v:2.1-9.10" */
module mux3(a, b, sel, y);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "mux3.v:2.20-2.21" */
  input a;
  wire a;
  /* src = "mux3.v:2.23-2.24" */
  input b;
  wire b;
  /* src = "mux3.v:2.26-2.29" */
  input sel;
  wire sel;
  /* src = "mux3.v:3.28-3.29" */
  output y;
  wire y;
  NOT _3_ (
    .A(sel),
    .Y(_0_)
  );
  AND _4_ (
    .A(sel),
    .B(b),
    .Y(_1_)
  );
  AND _5_ (
    .A(_0_),
    .B(a),
    .Y(_2_)
  );
  OR _6_ (
    .A(_1_),
    .B(_2_),
    .Y(y)
  );
endmodule
