/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "nand17.v:2.1-10.10" */
module nand17(a, b, out);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "nand17.v:3.22-3.23" */
  input [2:0] a;
  wire [2:0] a;
  /* src = "nand17.v:4.22-4.23" */
  input [2:0] b;
  wire [2:0] b;
  /* src = "nand17.v:5.23-5.26" */
  output [2:0] out;
  wire [2:0] out;
  AND _3_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_0_)
  );
  NOT _4_ (
    .A(_0_),
    .Y(out[0])
  );
  AND _5_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_1_)
  );
  NOT _6_ (
    .A(_1_),
    .Y(out[1])
  );
  AND _7_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_2_)
  );
  NOT _8_ (
    .A(_2_),
    .Y(out[2])
  );
endmodule
