/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "nand24.v:3.1-15.10" */
module nand24(a, b, c, d, e, f, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  /* src = "nand24.v:4.9-4.10" */
  input a;
  wire a;
  /* src = "nand24.v:5.9-5.10" */
  input b;
  wire b;
  /* src = "nand24.v:6.9-6.10" */
  input c;
  wire c;
  /* src = "nand24.v:7.9-7.10" */
  input d;
  wire d;
  /* src = "nand24.v:8.9-8.10" */
  input e;
  wire e;
  /* src = "nand24.v:9.9-9.10" */
  input f;
  wire f;
  /* src = "nand24.v:10.10-10.13" */
  output out;
  wire out;
  AND _05_ (
    .A(a),
    .B(b),
    .Y(_03_)
  );
  AND _06_ (
    .A(c),
    .B(d),
    .Y(_04_)
  );
  AND _07_ (
    .A(e),
    .B(f),
    .Y(_00_)
  );
  AND _08_ (
    .A(_04_),
    .B(_00_),
    .Y(_01_)
  );
  AND _09_ (
    .A(_03_),
    .B(_01_),
    .Y(_02_)
  );
  NOT _10_ (
    .A(_02_),
    .Y(out)
  );
endmodule
