/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "nand30.v:2.1-29.10" */
module nand30(a, b, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  /* src = "nand30.v:3.18-3.19" */
  input [15:0] a;
  wire [15:0] a;
  /* src = "nand30.v:4.18-4.19" */
  input [15:0] b;
  wire [15:0] b;
  /* src = "nand30.v:5.19-5.22" */
  output [15:0] out;
  wire [15:0] out;
  AND _16_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  NOT _17_ (
    .A(_00_),
    .Y(out[0])
  );
  AND _18_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_01_)
  );
  NOT _19_ (
    .A(_01_),
    .Y(out[1])
  );
  AND _20_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_02_)
  );
  NOT _21_ (
    .A(_02_),
    .Y(out[2])
  );
  AND _22_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_03_)
  );
  NOT _23_ (
    .A(_03_),
    .Y(out[3])
  );
  AND _24_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_04_)
  );
  NOT _25_ (
    .A(_04_),
    .Y(out[4])
  );
  AND _26_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_05_)
  );
  NOT _27_ (
    .A(_05_),
    .Y(out[5])
  );
  AND _28_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_06_)
  );
  NOT _29_ (
    .A(_06_),
    .Y(out[6])
  );
  AND _30_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_07_)
  );
  NOT _31_ (
    .A(_07_),
    .Y(out[7])
  );
  AND _32_ (
    .A(a[8]),
    .B(b[8]),
    .Y(_08_)
  );
  NOT _33_ (
    .A(_08_),
    .Y(out[8])
  );
  AND _34_ (
    .A(a[9]),
    .B(b[9]),
    .Y(_09_)
  );
  NOT _35_ (
    .A(_09_),
    .Y(out[9])
  );
  AND _36_ (
    .A(a[10]),
    .B(b[10]),
    .Y(_10_)
  );
  NOT _37_ (
    .A(_10_),
    .Y(out[10])
  );
  AND _38_ (
    .A(a[11]),
    .B(b[11]),
    .Y(_11_)
  );
  NOT _39_ (
    .A(_11_),
    .Y(out[11])
  );
  AND _40_ (
    .A(a[12]),
    .B(b[12]),
    .Y(_12_)
  );
  NOT _41_ (
    .A(_12_),
    .Y(out[12])
  );
  AND _42_ (
    .A(a[13]),
    .B(b[13]),
    .Y(_13_)
  );
  NOT _43_ (
    .A(_13_),
    .Y(out[13])
  );
  AND _44_ (
    .A(a[14]),
    .B(b[14]),
    .Y(_14_)
  );
  NOT _45_ (
    .A(_14_),
    .Y(out[14])
  );
  AND _46_ (
    .A(a[15]),
    .B(b[15]),
    .Y(_15_)
  );
  NOT _47_ (
    .A(_15_),
    .Y(out[15])
  );
endmodule
