/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "nand20_gate.v:2.1-15.10" */
module nand20_gate(a, b, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  /* src = "nand20_gate.v:3.22-3.23" */
  input [3:0] a;
  wire [3:0] a;
  /* src = "nand20_gate.v:4.22-4.23" */
  input [3:0] b;
  wire [3:0] b;
  /* src = "nand20_gate.v:5.22-5.25" */
  output [3:0] out;
  wire [3:0] out;
  AND _04_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  NOT _05_ (
    .A(_00_),
    .Y(out[0])
  );
  AND _06_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_01_)
  );
  NOT _07_ (
    .A(_01_),
    .Y(out[1])
  );
  AND _08_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_02_)
  );
  NOT _09_ (
    .A(_02_),
    .Y(out[2])
  );
  AND _10_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_03_)
  );
  NOT _11_ (
    .A(_03_),
    .Y(out[3])
  );
endmodule
