/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "nor15.v:2.1-21.10" */
module nor15(a, b, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  /* src = "nor15.v:3.22-3.23" */
  input [6:0] a;
  wire [6:0] a;
  /* src = "nor15.v:4.22-4.23" */
  input [6:0] b;
  wire [6:0] b;
  /* src = "nor15.v:5.22-5.25" */
  output [6:0] out;
  wire [6:0] out;
  OR _07_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_00_)
  );
  NOT _08_ (
    .A(_00_),
    .Y(out[3])
  );
  OR _09_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_01_)
  );
  NOT _10_ (
    .A(_01_),
    .Y(out[2])
  );
  OR _11_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_02_)
  );
  NOT _12_ (
    .A(_02_),
    .Y(out[1])
  );
  OR _13_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_03_)
  );
  NOT _14_ (
    .A(_03_),
    .Y(out[0])
  );
  OR _15_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_04_)
  );
  NOT _16_ (
    .A(_04_),
    .Y(out[6])
  );
  OR _17_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_05_)
  );
  NOT _18_ (
    .A(_05_),
    .Y(out[5])
  );
  OR _19_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_06_)
  );
  NOT _20_ (
    .A(_06_),
    .Y(out[4])
  );
endmodule
