/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "nor14.v:2.1-16.10" */
module nor14(a, b, out);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "nor14.v:3.22-3.23" */
  input [2:0] a;
  wire [2:0] a;
  /* src = "nor14.v:4.22-4.23" */
  input [2:0] b;
  wire [2:0] b;
  /* src = "nor14.v:5.22-5.25" */
  output [2:0] out;
  wire [2:0] out;
  OR _3_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_0_)
  );
  NOT _4_ (
    .A(_0_),
    .Y(out[2])
  );
  OR _5_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_1_)
  );
  NOT _6_ (
    .A(_1_),
    .Y(out[1])
  );
  OR _7_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_2_)
  );
  NOT _8_ (
    .A(_2_),
    .Y(out[0])
  );
endmodule
