/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "nor23.v:3.1-14.10" */
module nor23(a, b, c, d, e, out);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  /* src = "nor23.v:4.9-4.10" */
  input a;
  wire a;
  /* src = "nor23.v:5.9-5.10" */
  input b;
  wire b;
  /* src = "nor23.v:6.9-6.10" */
  input c;
  wire c;
  /* src = "nor23.v:7.9-7.10" */
  input d;
  wire d;
  /* src = "nor23.v:8.9-8.10" */
  input e;
  wire e;
  /* src = "nor23.v:9.10-9.13" */
  output out;
  wire out;
  OR _4_ (
    .A(a),
    .B(b),
    .Y(_1_)
  );
  OR _5_ (
    .A(c),
    .B(d),
    .Y(_2_)
  );
  OR _6_ (
    .A(e),
    .B(_2_),
    .Y(_3_)
  );
  OR _7_ (
    .A(_1_),
    .B(_3_),
    .Y(_0_)
  );
  NOT _8_ (
    .A(_0_),
    .Y(out)
  );
endmodule
