/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "not13.v:1.1-13.10" */
module not13(a, out);
  /* src = "not13.v:2.16-2.17" */
  input a;
  wire a;
  /* src = "not13.v:3.16-3.19" */
  output out;
  wire out;
  NOT _0_ (
    .A(a),
    .Y(out)
  );
endmodule
