/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "not6.v:1.1-10.10" */
module not6(in, out);
  /* src = "not6.v:2.9-2.11" */
  input in;
  wire in;
  /* src = "not6.v:3.14-3.17" */
  output out;
  wire out;
  NOT _0_ (
    .A(in),
    .Y(out)
  );
endmodule
