/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "or17_gate.v:2.1-29.10" */
module or17_gate(a, b, out);
  /* src = "or17_gate.v:3.17-3.18" */
  input [1:0] a;
  wire [1:0] a;
  /* src = "or17_gate.v:4.17-4.18" */
  input [1:0] b;
  wire [1:0] b;
  /* src = "or17_gate.v:5.22-5.25" */
  output [1:0] out;
  wire [1:0] out;
  OR _0_ (
    .A(b[0]),
    .B(a[0]),
    .Y(out[0])
  );
  OR _1_ (
    .A(b[1]),
    .B(a[1]),
    .Y(out[1])
  );
endmodule
