/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "or20.v:1.1-10.10" */
module or20(a, b, out);
  /* src = "or20.v:2.16-2.17" */
  input a;
  wire a;
  /* src = "or20.v:2.18-2.19" */
  input b;
  wire b;
  /* src = "or20.v:3.16-3.19" */
  output out;
  wire out;
  OR _0_ (
    .A(b),
    .B(a),
    .Y(out)
  );
endmodule
