/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "or22.v:2.1-15.10" */
module or22(a, b, out);
  /* src = "or22.v:3.17-3.18" */
  input [3:0] a;
  wire [3:0] a;
  /* src = "or22.v:4.17-4.18" */
  input [3:0] b;
  wire [3:0] b;
  /* src = "or22.v:5.18-5.21" */
  output [3:0] out;
  wire [3:0] out;
  OR _0_ (
    .A(a[1]),
    .B(b[1]),
    .Y(out[1])
  );
  OR _1_ (
    .A(a[2]),
    .B(b[2]),
    .Y(out[2])
  );
  OR _2_ (
    .A(a[3]),
    .B(b[3]),
    .Y(out[3])
  );
  OR _3_ (
    .A(a[0]),
    .B(b[0]),
    .Y(out[0])
  );
endmodule
