/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "or24.v:2.1-20.10" */
module or24(a, b, out);
  /* src = "or24.v:3.17-3.18" */
  input [7:0] a;
  wire [7:0] a;
  /* src = "or24.v:4.17-4.18" */
  input [7:0] b;
  wire [7:0] b;
  /* src = "or24.v:5.18-5.21" */
  output [7:0] out;
  wire [7:0] out;
  OR _0_ (
    .A(a[0]),
    .B(b[0]),
    .Y(out[0])
  );
  OR _1_ (
    .A(a[1]),
    .B(b[1]),
    .Y(out[1])
  );
  OR _2_ (
    .A(a[2]),
    .B(b[2]),
    .Y(out[2])
  );
  OR _3_ (
    .A(a[3]),
    .B(b[3]),
    .Y(out[3])
  );
  OR _4_ (
    .A(a[4]),
    .B(b[4]),
    .Y(out[4])
  );
  OR _5_ (
    .A(a[5]),
    .B(b[5]),
    .Y(out[5])
  );
  OR _6_ (
    .A(a[6]),
    .B(b[6]),
    .Y(out[6])
  );
  OR _7_ (
    .A(a[7]),
    .B(b[7]),
    .Y(out[7])
  );
endmodule
