/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "or28.v:1.1-12.10" */
module or28(a, b, c, d, e, out);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "or28.v:2.9-2.10" */
  input a;
  wire a;
  /* src = "or28.v:3.9-3.10" */
  input b;
  wire b;
  /* src = "or28.v:4.9-4.10" */
  input c;
  wire c;
  /* src = "or28.v:5.9-5.10" */
  input d;
  wire d;
  /* src = "or28.v:6.9-6.10" */
  input e;
  wire e;
  /* src = "or28.v:7.10-7.13" */
  output out;
  wire out;
  OR _3_ (
    .A(a),
    .B(b),
    .Y(_0_)
  );
  OR _4_ (
    .A(c),
    .B(d),
    .Y(_1_)
  );
  OR _5_ (
    .A(e),
    .B(_1_),
    .Y(_2_)
  );
  OR _6_ (
    .A(_0_),
    .B(_2_),
    .Y(out)
  );
endmodule
