/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "pe12.v:1.1-18.10" */
module pe12(D0, D1, D2, D3, en, Y1, Y0);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  /* src = "pe12.v:3.11-3.13" */
  input D0;
  wire D0;
  /* src = "pe12.v:3.14-3.16" */
  input D1;
  wire D1;
  /* src = "pe12.v:3.17-3.19" */
  input D2;
  wire D2;
  /* src = "pe12.v:3.20-3.22" */
  input D3;
  wire D3;
  /* src = "pe12.v:4.19-4.21" */
  output Y0;
  wire Y0;
  /* src = "pe12.v:4.16-4.18" */
  output Y1;
  wire Y1;
  /* src = "pe12.v:3.23-3.25" */
  input en;
  wire en;
  NOT _4_ (
    .A(D2),
    .Y(_2_)
  );
  OR _5_ (
    .A(D2),
    .B(D3),
    .Y(_3_)
  );
  AND _6_ (
    .A(en),
    .B(_3_),
    .Y(Y1)
  );
  AND _7_ (
    .A(D1),
    .B(_2_),
    .Y(_0_)
  );
  OR _8_ (
    .A(D3),
    .B(_0_),
    .Y(_1_)
  );
  AND _9_ (
    .A(en),
    .B(_1_),
    .Y(Y0)
  );
endmodule
