/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "pe13.v:1.1-17.10" */
module pe13(D0, D1, D2, D3, en, Y1, Y0, V);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  /* src = "pe13.v:3.11-3.13" */
  input D0;
  wire D0;
  /* src = "pe13.v:3.14-3.16" */
  input D1;
  wire D1;
  /* src = "pe13.v:3.17-3.19" */
  input D2;
  wire D2;
  /* src = "pe13.v:3.20-3.22" */
  input D3;
  wire D3;
  /* src = "pe13.v:4.22-4.23" */
  output V;
  wire V;
  /* src = "pe13.v:4.19-4.21" */
  output Y0;
  wire Y0;
  /* src = "pe13.v:4.16-4.18" */
  output Y1;
  wire Y1;
  /* src = "pe13.v:3.23-3.25" */
  input en;
  wire en;
  NOT _06_ (
    .A(D2),
    .Y(_05_)
  );
  OR _07_ (
    .A(D2),
    .B(D3),
    .Y(_00_)
  );
  AND _08_ (
    .A(en),
    .B(_00_),
    .Y(Y1)
  );
  OR _09_ (
    .A(D0),
    .B(D1),
    .Y(_01_)
  );
  OR _10_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  AND _11_ (
    .A(en),
    .B(_02_),
    .Y(V)
  );
  AND _12_ (
    .A(D1),
    .B(_05_),
    .Y(_03_)
  );
  OR _13_ (
    .A(D3),
    .B(_03_),
    .Y(_04_)
  );
  AND _14_ (
    .A(en),
    .B(_04_),
    .Y(Y0)
  );
endmodule
