/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "pe14.v:1.1-19.10" */
module pe14(en, i0, i1, i2, i3, i4, i5, i6, i7, y0, y1, y2);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  /* src = "pe14.v:3.11-3.13" */
  input en;
  wire en;
  /* src = "pe14.v:4.11-4.13" */
  input i0;
  wire i0;
  /* src = "pe14.v:4.14-4.16" */
  input i1;
  wire i1;
  /* src = "pe14.v:4.17-4.19" */
  input i2;
  wire i2;
  /* src = "pe14.v:4.20-4.22" */
  input i3;
  wire i3;
  /* src = "pe14.v:4.23-4.25" */
  input i4;
  wire i4;
  /* src = "pe14.v:4.26-4.28" */
  input i5;
  wire i5;
  /* src = "pe14.v:4.29-4.31" */
  input i6;
  wire i6;
  /* src = "pe14.v:4.32-4.34" */
  input i7;
  wire i7;
  /* src = "pe14.v:5.12-5.14" */
  output y0;
  wire y0;
  /* src = "pe14.v:5.15-5.17" */
  output y1;
  wire y1;
  /* src = "pe14.v:5.18-5.20" */
  output y2;
  wire y2;
  OR _08_ (
    .A(i6),
    .B(i7),
    .Y(_00_)
  );
  OR _09_ (
    .A(i2),
    .B(i3),
    .Y(_01_)
  );
  OR _10_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  AND _11_ (
    .A(en),
    .B(_02_),
    .Y(y1)
  );
  OR _12_ (
    .A(i7),
    .B(i3),
    .Y(_03_)
  );
  OR _13_ (
    .A(i5),
    .B(i1),
    .Y(_04_)
  );
  OR _14_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  AND _15_ (
    .A(en),
    .B(_05_),
    .Y(y0)
  );
  OR _16_ (
    .A(i4),
    .B(i5),
    .Y(_06_)
  );
  OR _17_ (
    .A(_00_),
    .B(_06_),
    .Y(_07_)
  );
  AND _18_ (
    .A(en),
    .B(_07_),
    .Y(y2)
  );
endmodule
