/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "pe15.v:1.1-11.10" */
module pe15(i0, i1, i2, i3, i4, i5, i6, i7, y0, y1, y2);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  /* src = "pe15.v:3.11-3.13" */
  input i0;
  wire i0;
  /* src = "pe15.v:3.14-3.16" */
  input i1;
  wire i1;
  /* src = "pe15.v:3.17-3.19" */
  input i2;
  wire i2;
  /* src = "pe15.v:3.20-3.22" */
  input i3;
  wire i3;
  /* src = "pe15.v:3.23-3.25" */
  input i4;
  wire i4;
  /* src = "pe15.v:3.26-3.28" */
  input i5;
  wire i5;
  /* src = "pe15.v:3.29-3.31" */
  input i6;
  wire i6;
  /* src = "pe15.v:3.32-3.34" */
  input i7;
  wire i7;
  /* src = "pe15.v:4.12-4.14" */
  output y0;
  wire y0;
  /* src = "pe15.v:4.15-4.17" */
  output y1;
  wire y1;
  /* src = "pe15.v:4.18-4.20" */
  output y2;
  wire y2;
  OR _05_ (
    .A(_00_),
    .B(_01_),
    .Y(y2)
  );
  OR _06_ (
    .A(i2),
    .B(i3),
    .Y(_03_)
  );
  OR _07_ (
    .A(_02_),
    .B(_03_),
    .Y(y1)
  );
  OR _08_ (
    .A(i3),
    .B(i1),
    .Y(_04_)
  );
  OR _09_ (
    .A(_00_),
    .B(_04_),
    .Y(y0)
  );
  OR _10_ (
    .A(i5),
    .B(i7),
    .Y(_00_)
  );
  OR _11_ (
    .A(i4),
    .B(i6),
    .Y(_01_)
  );
  OR _12_ (
    .A(i6),
    .B(i7),
    .Y(_02_)
  );
endmodule
