/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "pe21.v:1.1-12.10" */
module pe21(i, en, o, v);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  /* src = "pe21.v:3.11-3.13" */
  input en;
  wire en;
  /* src = "pe21.v:4.17-4.18" */
  input [3:0] i;
  wire [3:0] i;
  /* src = "pe21.v:5.18-5.19" */
  output [1:0] o;
  wire [1:0] o;
  /* src = "pe21.v:6.12-6.13" */
  output v;
  wire v;
  OR _05_ (
    .A(i[2]),
    .B(i[3]),
    .Y(_02_)
  );
  AND _06_ (
    .A(en),
    .B(_02_),
    .Y(o[1])
  );
  OR _07_ (
    .A(i[0]),
    .B(_02_),
    .Y(_03_)
  );
  AND _08_ (
    .A(en),
    .B(_03_),
    .Y(v)
  );
  NOT _09_ (
    .A(i[2]),
    .Y(_04_)
  );
  AND _10_ (
    .A(_04_),
    .B(i[1]),
    .Y(_00_)
  );
  OR _11_ (
    .A(i[3]),
    .B(_00_),
    .Y(_01_)
  );
  AND _12_ (
    .A(en),
    .B(_01_),
    .Y(o[0])
  );
endmodule
