/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "pe22.v:1.1-9.10" */
module pe22(i3, i2, i1, i0, en, o0, o1);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  /* src = "pe22.v:3.23-3.25" */
  input en;
  wire en;
  /* src = "pe22.v:3.20-3.22" */
  input i0;
  wire i0;
  /* src = "pe22.v:3.17-3.19" */
  input i1;
  wire i1;
  /* src = "pe22.v:3.14-3.16" */
  input i2;
  wire i2;
  /* src = "pe22.v:3.11-3.13" */
  input i3;
  wire i3;
  /* src = "pe22.v:4.12-4.14" */
  output o0;
  wire o0;
  /* src = "pe22.v:4.15-4.17" */
  output o1;
  wire o1;
  NOT _4_ (
    .A(i2),
    .Y(_1_)
  );
  AND _5_ (
    .A(_1_),
    .B(i1),
    .Y(_2_)
  );
  OR _6_ (
    .A(i3),
    .B(_2_),
    .Y(_3_)
  );
  AND _7_ (
    .A(en),
    .B(_3_),
    .Y(o0)
  );
  OR _8_ (
    .A(i2),
    .B(i3),
    .Y(_0_)
  );
  AND _9_ (
    .A(en),
    .B(_0_),
    .Y(o1)
  );
endmodule
