/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "pe3.v:1.1-19.10" */
module pe3(en, i, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  /* src = "pe3.v:3.11-3.13" */
  input en;
  wire en;
  /* src = "pe3.v:4.16-4.17" */
  input [7:0] i;
  wire [7:0] i;
  /* src = "pe3.v:5.17-5.18" */
  output [2:0] y;
  wire [2:0] y;
  OR _08_ (
    .A(i[6]),
    .B(i[7]),
    .Y(_00_)
  );
  OR _09_ (
    .A(i[2]),
    .B(i[3]),
    .Y(_01_)
  );
  OR _10_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  AND _11_ (
    .A(en),
    .B(_02_),
    .Y(y[1])
  );
  OR _12_ (
    .A(i[7]),
    .B(i[3]),
    .Y(_03_)
  );
  OR _13_ (
    .A(i[5]),
    .B(i[1]),
    .Y(_04_)
  );
  OR _14_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  AND _15_ (
    .A(en),
    .B(_05_),
    .Y(y[0])
  );
  OR _16_ (
    .A(i[4]),
    .B(i[5]),
    .Y(_06_)
  );
  OR _17_ (
    .A(_00_),
    .B(_06_),
    .Y(_07_)
  );
  AND _18_ (
    .A(en),
    .B(_07_),
    .Y(y[2])
  );
endmodule
