/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "sub12.v:2.1-20.10" */
module sub12(A, B, Diff, Borrow);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "sub12.v:3.7-3.8" */
  input A;
  wire A;
  /* src = "sub12.v:3.10-3.11" */
  input B;
  wire B;
  /* src = "sub12.v:4.18-4.24" */
  output Borrow;
  wire Borrow;
  /* src = "sub12.v:4.12-4.16" */
  output Diff;
  wire Diff;
  not _3_ (
    .A(A),
    .Y(_0_)
  );
  not _4_ (
    .A(B),
    .Y(_1_)
  );
  AND _5_ (
    .A(_0_),
    .B(B),
    .Y(Borrow)
  );
  AND _6_ (
    .A(A),
    .B(_1_),
    .Y(_2_)
  );
  OR _7_ (
    .A(Borrow),
    .B(_2_),
    .Y(Diff)
  );
endmodule
