/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "sub10.v:2.1-5.10" */
module sub10(a, b, D, B);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "sub10.v:2.37-2.38" */
  output B;
  wire B;
  /* src = "sub10.v:2.34-2.35" */
  output D;
  wire D;
  /* src = "sub10.v:2.21-2.22" */
  input a;
  wire a;
  /* src = "sub10.v:2.24-2.25" */
  input b;
  wire b;
  not _3_ (
    .A(a),
    .Y(_0_)
  );
  not _4_ (
    .A(b),
    .Y(_1_)
  );
  AND _5_ (
    .A(_0_),
    .B(b),
    .Y(B)
  );
  AND _6_ (
    .A(a),
    .B(_1_),
    .Y(_2_)
  );
  OR _7_ (
    .A(B),
    .B(_2_),
    .Y(D)
  );
endmodule
