/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "sub2.v:2.1-17.10" */
module sub2(a, b, c, borrow, difference);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  /* src = "sub2.v:4.7-4.8" */
  input a;
  wire a;
  /* src = "sub2.v:5.7-5.8" */
  input b;
  wire b;
  /* src = "sub2.v:7.8-7.14" */
  output borrow;
  wire borrow;
  /* src = "sub2.v:6.7-6.8" */
  input c;
  wire c;
  /* src = "sub2.v:8.8-8.18" */
  output difference;
  wire difference;
  OR _12_ (
    .A(a),
    .B(_09_),
    .Y(_00_)
  );
  AND _13_ (
    .A(a),
    .B(_09_),
    .Y(_01_)
  );
  OR _14_ (
    .A(_08_),
    .B(b),
    .Y(_02_)
  );
  AND _15_ (
    .A(_00_),
    .B(_02_),
    .Y(_03_)
  );
  OR _16_ (
    .A(_11_),
    .B(_01_),
    .Y(_04_)
  );
  OR _17_ (
    .A(_10_),
    .B(_03_),
    .Y(_05_)
  );
  OR _18_ (
    .A(c),
    .B(_04_),
    .Y(_06_)
  );
  AND _19_ (
    .A(_05_),
    .B(_06_),
    .Y(difference)
  );
  OR _20_ (
    .A(c),
    .B(_11_),
    .Y(_07_)
  );
  AND _21_ (
    .A(_02_),
    .B(_07_),
    .Y(borrow)
  );
  NOT _22_ (
    .A(a),
    .Y(_08_)
  );
  NOT _23_ (
    .A(b),
    .Y(_09_)
  );
  NOT _24_ (
    .A(c),
    .Y(_10_)
  );
  AND _25_ (
    .A(_08_),
    .B(b),
    .Y(_11_)
  );
endmodule
