/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "sub7.v:2.1-42.10" */
module sub7(A, B, Bin, D, Bout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "sub7.v:3.11-3.12" */
  input A;
  wire A;
  /* src = "sub7.v:3.13-3.14" */
  input B;
  wire B;
  /* src = "sub7.v:3.15-3.18" */
  input Bin;
  wire Bin;
  /* src = "sub7.v:4.18-4.22" */
  output Bout;
  wire Bout;
  /* src = "sub7.v:4.16-4.17" */
  output D;
  wire D;
  NOT _09_ (
    .A(A),
    .Y(_05_)
  );
  OR _10_ (
    .A(Bin),
    .B(B),
    .Y(_06_)
  );
  NOT _11_ (
    .A(_06_),
    .Y(_07_)
  );
  AND _12_ (
    .A(A),
    .B(_07_),
    .Y(_08_)
  );
  AND _13_ (
    .A(Bin),
    .B(B),
    .Y(_00_)
  );
  NOT _14_ (
    .A(_00_),
    .Y(_01_)
  );
  OR _15_ (
    .A(A),
    .B(_01_),
    .Y(_02_)
  );
  AND _16_ (
    .A(_05_),
    .B(_06_),
    .Y(_03_)
  );
  OR _17_ (
    .A(_00_),
    .B(_03_),
    .Y(Bout)
  );
  OR _18_ (
    .A(_08_),
    .B(Bout),
    .Y(_04_)
  );
  AND _19_ (
    .A(_02_),
    .B(_04_),
    .Y(D)
  );
endmodule
