/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "sub8.v:2.1-5.10" */
module sub8(D, B, X, Y, Z);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "sub8.v:2.24-2.25" */
  output B;
  wire B;
  /* src = "sub8.v:2.21-2.22" */
  output D;
  wire D;
  /* src = "sub8.v:2.33-2.34" */
  input X;
  wire X;
  /* src = "sub8.v:2.36-2.37" */
  input Y;
  wire Y;
  /* src = "sub8.v:2.39-2.40" */
  input Z;
  wire Z;
  AND _09_ (
    .A(_05_),
    .B(_01_),
    .Y(_03_)
  );
  AND _10_ (
    .A(X),
    .B(_02_),
    .Y(_04_)
  );
  OR _11_ (
    .A(_03_),
    .B(_04_),
    .Y(D)
  );
  OR _12_ (
    .A(_06_),
    .B(_03_),
    .Y(B)
  );
  NOT _13_ (
    .A(X),
    .Y(_05_)
  );
  AND _14_ (
    .A(Y),
    .B(Z),
    .Y(_06_)
  );
  NOT _15_ (
    .A(_06_),
    .Y(_07_)
  );
  OR _16_ (
    .A(Y),
    .B(Z),
    .Y(_08_)
  );
  NOT _17_ (
    .A(_08_),
    .Y(_00_)
  );
  AND _18_ (
    .A(_07_),
    .B(_08_),
    .Y(_01_)
  );
  OR _19_ (
    .A(_06_),
    .B(_00_),
    .Y(_02_)
  );
endmodule
