/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "sub9.v:2.1-5.10" */
module sub9(a, b, Bin, D, Bout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  /* src = "sub9.v:2.26-2.29" */
  input Bin;
  wire Bin;
  /* src = "sub9.v:2.41-2.45" */
  output Bout;
  wire Bout;
  /* src = "sub9.v:2.38-2.39" */
  output D;
  wire D;
  /* src = "sub9.v:2.20-2.21" */
  input a;
  wire a;
  /* src = "sub9.v:2.23-2.24" */
  input b;
  wire b;
  OR _11_ (
    .A(_07_),
    .B(b),
    .Y(_02_)
  );
  AND _12_ (
    .A(_00_),
    .B(_02_),
    .Y(_03_)
  );
  OR _13_ (
    .A(_10_),
    .B(_01_),
    .Y(_04_)
  );
  AND _14_ (
    .A(Bin),
    .B(_03_),
    .Y(_05_)
  );
  AND _15_ (
    .A(_08_),
    .B(_04_),
    .Y(_06_)
  );
  OR _16_ (
    .A(_05_),
    .B(_06_),
    .Y(D)
  );
  OR _17_ (
    .A(_10_),
    .B(_05_),
    .Y(Bout)
  );
  not _18_ (
    .A(a),
    .Y(_07_)
  );
  not _19_ (
    .A(Bin),
    .Y(_08_)
  );
  not _20_ (
    .A(b),
    .Y(_09_)
  );
  AND _21_ (
    .A(_07_),
    .B(b),
    .Y(_10_)
  );
  OR _22_ (
    .A(a),
    .B(_09_),
    .Y(_00_)
  );
  AND _23_ (
    .A(a),
    .B(_09_),
    .Y(_01_)
  );
endmodule
