/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "xnor18.v:1.1-14.10" */
module xnor18(a, b, c, d, e, f, g, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  /* src = "xnor18.v:2.16-2.17" */
  input a;
  wire a;
  /* src = "xnor18.v:3.16-3.17" */
  input b;
  wire b;
  /* src = "xnor18.v:4.16-4.17" */
  input c;
  wire c;
  /* src = "xnor18.v:5.16-5.17" */
  input d;
  wire d;
  /* src = "xnor18.v:6.16-6.17" */
  input e;
  wire e;
  /* src = "xnor18.v:7.16-7.17" */
  input f;
  wire f;
  /* src = "xnor18.v:8.16-8.17" */
  input g;
  wire g;
  /* src = "xnor18.v:9.17-9.20" */
  output out;
  wire out;
  AND _35_ (
    .A(_03_),
    .B(_04_),
    .Y(_06_)
  );
  OR _36_ (
    .A(_02_),
    .B(_05_),
    .Y(_07_)
  );
  AND _37_ (
    .A(d),
    .B(_06_),
    .Y(_08_)
  );
  OR _38_ (
    .A(_00_),
    .B(_07_),
    .Y(_09_)
  );
  AND _39_ (
    .A(_00_),
    .B(_07_),
    .Y(_10_)
  );
  OR _40_ (
    .A(d),
    .B(_06_),
    .Y(_11_)
  );
  AND _41_ (
    .A(_09_),
    .B(_11_),
    .Y(_12_)
  );
  OR _42_ (
    .A(_08_),
    .B(_10_),
    .Y(_13_)
  );
  AND _43_ (
    .A(e),
    .B(f),
    .Y(_14_)
  );
  NOT _44_ (
    .A(_14_),
    .Y(_15_)
  );
  OR _45_ (
    .A(e),
    .B(f),
    .Y(_16_)
  );
  NOT _46_ (
    .A(_16_),
    .Y(_17_)
  );
  OR _47_ (
    .A(_14_),
    .B(_17_),
    .Y(_18_)
  );
  AND _48_ (
    .A(_15_),
    .B(_16_),
    .Y(_19_)
  );
  AND _49_ (
    .A(_34_),
    .B(g),
    .Y(_20_)
  );
  OR _50_ (
    .A(c),
    .B(_01_),
    .Y(_21_)
  );
  AND _51_ (
    .A(c),
    .B(_01_),
    .Y(_22_)
  );
  OR _52_ (
    .A(_34_),
    .B(g),
    .Y(_23_)
  );
  AND _53_ (
    .A(_21_),
    .B(_23_),
    .Y(_24_)
  );
  OR _54_ (
    .A(_20_),
    .B(_22_),
    .Y(_25_)
  );
  AND _55_ (
    .A(_18_),
    .B(_25_),
    .Y(_26_)
  );
  OR _56_ (
    .A(_19_),
    .B(_24_),
    .Y(_27_)
  );
  AND _57_ (
    .A(_19_),
    .B(_24_),
    .Y(_28_)
  );
  OR _58_ (
    .A(_18_),
    .B(_25_),
    .Y(_29_)
  );
  AND _59_ (
    .A(_27_),
    .B(_29_),
    .Y(_30_)
  );
  OR _60_ (
    .A(_26_),
    .B(_28_),
    .Y(_31_)
  );
  OR _61_ (
    .A(_12_),
    .B(_30_),
    .Y(_32_)
  );
  OR _62_ (
    .A(_13_),
    .B(_31_),
    .Y(_33_)
  );
  AND _63_ (
    .A(_32_),
    .B(_33_),
    .Y(out)
  );
  NOT _64_ (
    .A(c),
    .Y(_34_)
  );
  NOT _65_ (
    .A(d),
    .Y(_00_)
  );
  NOT _66_ (
    .A(g),
    .Y(_01_)
  );
  AND _67_ (
    .A(a),
    .B(b),
    .Y(_02_)
  );
  NOT _68_ (
    .A(_02_),
    .Y(_03_)
  );
  OR _69_ (
    .A(a),
    .B(b),
    .Y(_04_)
  );
  NOT _70_ (
    .A(_04_),
    .Y(_05_)
  );
endmodule
