/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "xnor15.v:1.1-11.10" */
module xnor15(a, b, c, d, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  /* src = "xnor15.v:2.16-2.17" */
  input a;
  wire a;
  /* src = "xnor15.v:3.16-3.17" */
  input b;
  wire b;
  /* src = "xnor15.v:4.16-4.17" */
  input c;
  wire c;
  /* src = "xnor15.v:5.16-5.17" */
  input d;
  wire d;
  /* src = "xnor15.v:6.17-6.20" */
  output out;
  wire out;
  OR _14_ (
    .A(_01_),
    .B(_07_),
    .Y(_09_)
  );
  AND _15_ (
    .A(_08_),
    .B(_09_),
    .Y(out)
  );
  OR _16_ (
    .A(c),
    .B(d),
    .Y(_10_)
  );
  not _17_ (
    .A(_10_),
    .Y(_11_)
  );
  AND _18_ (
    .A(c),
    .B(d),
    .Y(_12_)
  );
  not _19_ (
    .A(_12_),
    .Y(_13_)
  );
  AND _20_ (
    .A(_10_),
    .B(_13_),
    .Y(_00_)
  );
  OR _21_ (
    .A(_11_),
    .B(_12_),
    .Y(_01_)
  );
  AND _22_ (
    .A(a),
    .B(b),
    .Y(_02_)
  );
  not _23_ (
    .A(_02_),
    .Y(_03_)
  );
  OR _24_ (
    .A(a),
    .B(b),
    .Y(_04_)
  );
  not _25_ (
    .A(_04_),
    .Y(_05_)
  );
  OR _26_ (
    .A(_02_),
    .B(_05_),
    .Y(_06_)
  );
  AND _27_ (
    .A(_03_),
    .B(_04_),
    .Y(_07_)
  );
  OR _28_ (
    .A(_00_),
    .B(_06_),
    .Y(_08_)
  );
endmodule
