/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "xnor25.v:2.1-10.10" */
module xnor25(a, b, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "xnor25.v:3.22-3.23" */
  input [2:0] a;
  wire [2:0] a;
  /* src = "xnor25.v:4.22-4.23" */
  input [2:0] b;
  wire [2:0] b;
  /* src = "xnor25.v:5.23-5.26" */
  output [2:0] out;
  wire [2:0] out;
  NOT _09_ (
    .A(_06_),
    .Y(_07_)
  );
  AND _10_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_08_)
  );
  OR _11_ (
    .A(_07_),
    .B(_08_),
    .Y(out[2])
  );
  OR _12_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  NOT _13_ (
    .A(_00_),
    .Y(_01_)
  );
  AND _14_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_02_)
  );
  OR _15_ (
    .A(_01_),
    .B(_02_),
    .Y(out[0])
  );
  OR _16_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_03_)
  );
  NOT _17_ (
    .A(_03_),
    .Y(_04_)
  );
  AND _18_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_05_)
  );
  OR _19_ (
    .A(_04_),
    .B(_05_),
    .Y(out[1])
  );
  OR _20_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_06_)
  );
endmodule
