/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "xor10.v:1.1-13.10" */
module xor10(a, b, c, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "xor10.v:2.9-2.10" */
  input a;
  wire a;
  /* src = "xor10.v:3.9-3.10" */
  input b;
  wire b;
  /* src = "xor10.v:4.9-4.10" */
  input c;
  wire c;
  /* src = "xor10.v:5.14-5.17" */
  output out;
  wire out;
  NOT _09_ (
    .A(c),
    .Y(_04_)
  );
  OR _10_ (
    .A(b),
    .B(a),
    .Y(_05_)
  );
  NOT _11_ (
    .A(_05_),
    .Y(_06_)
  );
  AND _12_ (
    .A(b),
    .B(a),
    .Y(_07_)
  );
  NOT _13_ (
    .A(_07_),
    .Y(_08_)
  );
  AND _14_ (
    .A(_05_),
    .B(_08_),
    .Y(_00_)
  );
  OR _15_ (
    .A(_06_),
    .B(_07_),
    .Y(_01_)
  );
  OR _16_ (
    .A(_04_),
    .B(_01_),
    .Y(_02_)
  );
  OR _17_ (
    .A(c),
    .B(_00_),
    .Y(_03_)
  );
  AND _18_ (
    .A(_02_),
    .B(_03_),
    .Y(out)
  );
endmodule
