/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "xor27.v:1.1-13.10" */
module xor27(a, b, c, d, e, f, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  /* src = "xor27.v:2.16-2.17" */
  input a;
  wire a;
  /* src = "xor27.v:3.16-3.17" */
  input b;
  wire b;
  /* src = "xor27.v:4.16-4.17" */
  input c;
  wire c;
  /* src = "xor27.v:5.16-5.17" */
  input d;
  wire d;
  /* src = "xor27.v:6.16-6.17" */
  input e;
  wire e;
  /* src = "xor27.v:7.16-7.17" */
  input f;
  wire f;
  /* src = "xor27.v:8.17-8.20" */
  output out;
  wire out;
  AND _26_ (
    .A(_05_),
    .B(_06_),
    .Y(_09_)
  );
  AND _27_ (
    .A(_03_),
    .B(_08_),
    .Y(_10_)
  );
  OR _28_ (
    .A(_02_),
    .B(_09_),
    .Y(_11_)
  );
  AND _29_ (
    .A(_02_),
    .B(_09_),
    .Y(_12_)
  );
  OR _30_ (
    .A(_03_),
    .B(_08_),
    .Y(_13_)
  );
  AND _31_ (
    .A(_11_),
    .B(_13_),
    .Y(_14_)
  );
  OR _32_ (
    .A(_10_),
    .B(_12_),
    .Y(_15_)
  );
  OR _33_ (
    .A(e),
    .B(f),
    .Y(_16_)
  );
  NOT _34_ (
    .A(_16_),
    .Y(_17_)
  );
  AND _35_ (
    .A(e),
    .B(f),
    .Y(_18_)
  );
  NOT _36_ (
    .A(_18_),
    .Y(_19_)
  );
  AND _37_ (
    .A(_16_),
    .B(_19_),
    .Y(_20_)
  );
  OR _38_ (
    .A(_17_),
    .B(_18_),
    .Y(_21_)
  );
  OR _39_ (
    .A(_15_),
    .B(_21_),
    .Y(_22_)
  );
  OR _40_ (
    .A(_14_),
    .B(_20_),
    .Y(_23_)
  );
  AND _41_ (
    .A(_22_),
    .B(_23_),
    .Y(out)
  );
  OR _42_ (
    .A(c),
    .B(d),
    .Y(_24_)
  );
  NOT _43_ (
    .A(_24_),
    .Y(_25_)
  );
  AND _44_ (
    .A(c),
    .B(d),
    .Y(_00_)
  );
  NOT _45_ (
    .A(_00_),
    .Y(_01_)
  );
  AND _46_ (
    .A(_24_),
    .B(_01_),
    .Y(_02_)
  );
  OR _47_ (
    .A(_25_),
    .B(_00_),
    .Y(_03_)
  );
  AND _48_ (
    .A(a),
    .B(b),
    .Y(_04_)
  );
  NOT _49_ (
    .A(_04_),
    .Y(_05_)
  );
  OR _50_ (
    .A(a),
    .B(b),
    .Y(_06_)
  );
  NOT _51_ (
    .A(_06_),
    .Y(_07_)
  );
  OR _52_ (
    .A(_04_),
    .B(_07_),
    .Y(_08_)
  );
endmodule
