/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "xor5.v:2.1-9.10" */
module xor5(a, b, out);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "xor5.v:3.16-3.17" */
  input a;
  wire a;
  /* src = "xor5.v:3.18-3.19" */
  input b;
  wire b;
  /* src = "xor5.v:4.17-4.20" */
  output out;
  wire out;
  OR _3_ (
    .A(b),
    .B(a),
    .Y(_0_)
  );
  AND _4_ (
    .A(b),
    .B(a),
    .Y(_1_)
  );
  NOT _5_ (
    .A(_1_),
    .Y(_2_)
  );
  AND _6_ (
    .A(_0_),
    .B(_2_),
    .Y(out)
  );
endmodule
