/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "adder9.v:2.1-11.10" */
module adder9(A0, A1, B0, B1, Sum, Cin, Cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  /* src = "adder9.v:4.11-4.13" */
  input A0;
  wire A0;
  /* src = "adder9.v:4.14-4.16" */
  input A1;
  wire A1;
  /* src = "adder9.v:4.17-4.19" */
  input B0;
  wire B0;
  /* src = "adder9.v:4.20-4.22" */
  input B1;
  wire B1;
  /* src = "adder9.v:6.11-6.14" */
  input Cin;
  wire Cin;
  /* src = "adder9.v:7.12-7.16" */
  output Cout;
  wire Cout;
  /* src = "adder9.v:5.18-5.21" */
  output [1:0] Sum;
  wire [1:0] Sum;
  not _23_ (
    .A(B0),
    .Y(_22_)
  );
  not _24_ (
    .A(A0),
    .Y(_00_)
  );
  not _25_ (
    .A(Cin),
    .Y(_01_)
  );
  OR _26_ (
    .A(B1),
    .B(A1),
    .Y(_02_)
  );
  not _27_ (
    .A(_02_),
    .Y(_03_)
  );
  AND _28_ (
    .A(B0),
    .B(A0),
    .Y(_04_)
  );
  OR _29_ (
    .A(_22_),
    .B(_00_),
    .Y(_05_)
  );
  OR _30_ (
    .A(B0),
    .B(A0),
    .Y(_06_)
  );
  not _31_ (
    .A(_06_),
    .Y(_07_)
  );
  AND _32_ (
    .A(_05_),
    .B(_06_),
    .Y(_08_)
  );
  OR _33_ (
    .A(_04_),
    .B(_07_),
    .Y(_09_)
  );
  AND _34_ (
    .A(Cin),
    .B(_08_),
    .Y(_10_)
  );
  OR _35_ (
    .A(_01_),
    .B(_09_),
    .Y(_11_)
  );
  AND _36_ (
    .A(_05_),
    .B(_11_),
    .Y(_12_)
  );
  OR _37_ (
    .A(_04_),
    .B(_10_),
    .Y(_13_)
  );
  AND _38_ (
    .A(B1),
    .B(A1),
    .Y(_14_)
  );
  not _39_ (
    .A(_14_),
    .Y(_15_)
  );
  OR _40_ (
    .A(_13_),
    .B(_14_),
    .Y(_16_)
  );
  AND _41_ (
    .A(_02_),
    .B(_15_),
    .Y(_17_)
  );
  OR _42_ (
    .A(_03_),
    .B(_14_),
    .Y(_18_)
  );
  AND _43_ (
    .A(_12_),
    .B(_17_),
    .Y(_19_)
  );
  AND _44_ (
    .A(_13_),
    .B(_18_),
    .Y(_20_)
  );
  OR _45_ (
    .A(_19_),
    .B(_20_),
    .Y(Sum[1])
  );
  AND _46_ (
    .A(_02_),
    .B(_16_),
    .Y(Cout)
  );
  OR _47_ (
    .A(Cin),
    .B(_08_),
    .Y(_21_)
  );
  AND _48_ (
    .A(_11_),
    .B(_21_),
    .Y(Sum[0])
  );
endmodule
