/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "and12_gate.v:2.1-17.10" */
module and12_gate(a, b, out);
  /* src = "and12_gate.v:3.22-3.23" */
  input [3:0] a;
  wire [3:0] a;
  /* src = "and12_gate.v:4.22-4.23" */
  input [3:0] b;
  wire [3:0] b;
  /* src = "and12_gate.v:5.22-5.25" */
  output [3:0] out;
  wire [3:0] out;
  AND _0_ (
    .A(a[0]),
    .B(b[0]),
    .Y(out[0])
  );
  AND _1_ (
    .A(a[1]),
    .B(b[1]),
    .Y(out[1])
  );
  AND _2_ (
    .A(a[2]),
    .B(b[2]),
    .Y(out[2])
  );
  AND _3_ (
    .A(a[3]),
    .B(b[3]),
    .Y(out[3])
  );
endmodule
