/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "decoder27.v:1.1-24.10" */
module decoder27(d_out, d_in);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  /* src = "decoder27.v:4.19-4.23" */
  input [3:0] d_in;
  wire [3:0] d_in;
  /* src = "decoder27.v:3.19-3.24" */
  output [15:0] d_out;
  wire [15:0] d_out;
  not _12_ (
    .A(d_in[0]),
    .Y(_00_)
  );
  not _13_ (
    .A(d_in[1]),
    .Y(_01_)
  );
  not _14_ (
    .A(d_in[2]),
    .Y(_02_)
  );
  not _15_ (
    .A(d_in[3]),
    .Y(_03_)
  );
  AND _16_ (
    .A(_00_),
    .B(_01_),
    .Y(_04_)
  );
  AND _17_ (
    .A(_02_),
    .B(_03_),
    .Y(_05_)
  );
  AND _18_ (
    .A(_04_),
    .B(_05_),
    .Y(d_out[0])
  );
  AND _19_ (
    .A(d_in[0]),
    .B(_01_),
    .Y(_06_)
  );
  AND _20_ (
    .A(_05_),
    .B(_06_),
    .Y(d_out[1])
  );
  AND _21_ (
    .A(_00_),
    .B(d_in[1]),
    .Y(_07_)
  );
  AND _22_ (
    .A(_05_),
    .B(_07_),
    .Y(d_out[2])
  );
  AND _23_ (
    .A(d_in[0]),
    .B(d_in[1]),
    .Y(_08_)
  );
  AND _24_ (
    .A(_05_),
    .B(_08_),
    .Y(d_out[3])
  );
  AND _25_ (
    .A(d_in[2]),
    .B(_03_),
    .Y(_09_)
  );
  AND _26_ (
    .A(_04_),
    .B(_09_),
    .Y(d_out[4])
  );
  AND _27_ (
    .A(_06_),
    .B(_09_),
    .Y(d_out[5])
  );
  AND _28_ (
    .A(_07_),
    .B(_09_),
    .Y(d_out[6])
  );
  AND _29_ (
    .A(_08_),
    .B(_09_),
    .Y(d_out[7])
  );
  AND _30_ (
    .A(_02_),
    .B(d_in[3]),
    .Y(_10_)
  );
  AND _31_ (
    .A(_04_),
    .B(_10_),
    .Y(d_out[8])
  );
  AND _32_ (
    .A(_06_),
    .B(_10_),
    .Y(d_out[9])
  );
  AND _33_ (
    .A(_07_),
    .B(_10_),
    .Y(d_out[10])
  );
  AND _34_ (
    .A(_08_),
    .B(_10_),
    .Y(d_out[11])
  );
  AND _35_ (
    .A(d_in[2]),
    .B(d_in[3]),
    .Y(_11_)
  );
  AND _36_ (
    .A(_04_),
    .B(_11_),
    .Y(d_out[12])
  );
  AND _37_ (
    .A(_06_),
    .B(_11_),
    .Y(d_out[13])
  );
  AND _38_ (
    .A(_07_),
    .B(_11_),
    .Y(d_out[14])
  );
  AND _39_ (
    .A(_08_),
    .B(_11_),
    .Y(d_out[15])
  );
endmodule
