/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "encoder10.v:1.1-14.10" */
module encoder10(a, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  /* src = "encoder10.v:2.17-2.18" */
  input [3:0] a;
  wire [3:0] a;
  /* src = "encoder10.v:3.22-3.23" */
  output [1:0] y;
  wire [1:0] y;
  AND _11_ (
    .A(a[3]),
    .B(a[1]),
    .Y(_08_)
  );
  not _12_ (
    .A(_08_),
    .Y(_09_)
  );
  OR _13_ (
    .A(a[2]),
    .B(a[0]),
    .Y(_10_)
  );
  not _14_ (
    .A(_10_),
    .Y(_00_)
  );
  OR _15_ (
    .A(a[3]),
    .B(a[1]),
    .Y(_01_)
  );
  AND _16_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  OR _17_ (
    .A(a[1]),
    .B(a[0]),
    .Y(_03_)
  );
  AND _18_ (
    .A(_09_),
    .B(_02_),
    .Y(y[0])
  );
  OR _19_ (
    .A(a[2]),
    .B(a[3]),
    .Y(_04_)
  );
  AND _20_ (
    .A(a[2]),
    .B(a[3]),
    .Y(_05_)
  );
  OR _21_ (
    .A(_03_),
    .B(_05_),
    .Y(_06_)
  );
  not _22_ (
    .A(_06_),
    .Y(_07_)
  );
  AND _23_ (
    .A(_04_),
    .B(_07_),
    .Y(y[1])
  );
endmodule
