/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mult30.v:2.1-16.10" */
module mult30(A, B, C);
  /* src = "mult30.v:4.18-4.19" */
  input [31:0] A;
  wire [31:0] A;
  /* src = "mult30.v:5.11-5.12" */
  input B;
  wire B;
  /* src = "mult30.v:6.23-6.24" */
  output [31:0] C;
  wire [31:0] C;
  AND _00_ (
    .A(A[17]),
    .B(B),
    .Y(C[17])
  );
  AND _01_ (
    .A(B),
    .B(A[18]),
    .Y(C[18])
  );
  AND _02_ (
    .A(B),
    .B(A[19]),
    .Y(C[19])
  );
  AND _03_ (
    .A(B),
    .B(A[20]),
    .Y(C[20])
  );
  AND _04_ (
    .A(B),
    .B(A[21]),
    .Y(C[21])
  );
  AND _05_ (
    .A(B),
    .B(A[22]),
    .Y(C[22])
  );
  AND _06_ (
    .A(B),
    .B(A[23]),
    .Y(C[23])
  );
  AND _07_ (
    .A(B),
    .B(A[24]),
    .Y(C[24])
  );
  AND _08_ (
    .A(B),
    .B(A[25]),
    .Y(C[25])
  );
  AND _09_ (
    .A(B),
    .B(A[26]),
    .Y(C[26])
  );
  AND _10_ (
    .A(B),
    .B(A[27]),
    .Y(C[27])
  );
  AND _11_ (
    .A(B),
    .B(A[28]),
    .Y(C[28])
  );
  AND _12_ (
    .A(B),
    .B(A[29]),
    .Y(C[29])
  );
  AND _13_ (
    .A(B),
    .B(A[30]),
    .Y(C[30])
  );
  AND _14_ (
    .A(B),
    .B(A[31]),
    .Y(C[31])
  );
  AND _15_ (
    .A(B),
    .B(A[0]),
    .Y(C[0])
  );
  AND _16_ (
    .A(B),
    .B(A[1]),
    .Y(C[1])
  );
  AND _17_ (
    .A(B),
    .B(A[2]),
    .Y(C[2])
  );
  AND _18_ (
    .A(B),
    .B(A[3]),
    .Y(C[3])
  );
  AND _19_ (
    .A(B),
    .B(A[4]),
    .Y(C[4])
  );
  AND _20_ (
    .A(B),
    .B(A[5]),
    .Y(C[5])
  );
  AND _21_ (
    .A(B),
    .B(A[6]),
    .Y(C[6])
  );
  AND _22_ (
    .A(B),
    .B(A[7]),
    .Y(C[7])
  );
  AND _23_ (
    .A(B),
    .B(A[8]),
    .Y(C[8])
  );
  AND _24_ (
    .A(B),
    .B(A[9]),
    .Y(C[9])
  );
  AND _25_ (
    .A(B),
    .B(A[10]),
    .Y(C[10])
  );
  AND _26_ (
    .A(B),
    .B(A[11]),
    .Y(C[11])
  );
  AND _27_ (
    .A(B),
    .B(A[12]),
    .Y(C[12])
  );
  AND _28_ (
    .A(B),
    .B(A[13]),
    .Y(C[13])
  );
  AND _29_ (
    .A(B),
    .B(A[14]),
    .Y(C[14])
  );
  AND _30_ (
    .A(B),
    .B(A[15]),
    .Y(C[15])
  );
  AND _31_ (
    .A(B),
    .B(A[16]),
    .Y(C[16])
  );
endmodule
