/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mult14.v:1.1-15.10" */
module mult14(a, b, result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  /* src = "mult14.v:2.17-2.18" */
  input [1:0] a;
  wire [1:0] a;
  /* src = "mult14.v:3.17-3.18" */
  input [1:0] b;
  wire [1:0] b;
  /* src = "mult14.v:4.22-4.28" */
  output [3:0] result;
  wire [3:0] result;
  AND _06_ (
    .A(b[0]),
    .B(a[1]),
    .Y(_05_)
  );
  AND _07_ (
    .A(b[1]),
    .B(a[0]),
    .Y(_00_)
  );
  OR _08_ (
    .A(_05_),
    .B(_00_),
    .Y(_01_)
  );
  AND _09_ (
    .A(a[0]),
    .B(b[0]),
    .Y(result[0])
  );
  not _10_ (
    .A(result[0]),
    .Y(_02_)
  );
  AND _11_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_03_)
  );
  AND _12_ (
    .A(result[0]),
    .B(_03_),
    .Y(result[3])
  );
  not _13_ (
    .A(result[3]),
    .Y(_04_)
  );
  AND _14_ (
    .A(_01_),
    .B(_04_),
    .Y(result[1])
  );
  AND _15_ (
    .A(_02_),
    .B(_03_),
    .Y(result[2])
  );
endmodule
