/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mux11.v:3.1-14.10" */
module mux11(a, b, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  /* src = "mux11.v:3.27-3.28" */
  input [6:0] a;
  wire [6:0] a;
  /* src = "mux11.v:3.30-3.31" */
  input [6:0] b;
  wire [6:0] b;
  /* src = "mux11.v:4.19-4.22" */
  input sel;
  wire sel;
  /* src = "mux11.v:5.30-5.31" */
  output [6:0] y;
  wire [6:0] y;
  not _15_ (
    .A(sel),
    .Y(_00_)
  );
  AND _16_ (
    .A(sel),
    .B(b[3]),
    .Y(_01_)
  );
  AND _17_ (
    .A(_00_),
    .B(a[3]),
    .Y(_02_)
  );
  OR _18_ (
    .A(_01_),
    .B(_02_),
    .Y(y[3])
  );
  AND _19_ (
    .A(sel),
    .B(b[2]),
    .Y(_03_)
  );
  AND _20_ (
    .A(_00_),
    .B(a[2]),
    .Y(_04_)
  );
  OR _21_ (
    .A(_03_),
    .B(_04_),
    .Y(y[2])
  );
  AND _22_ (
    .A(sel),
    .B(b[1]),
    .Y(_05_)
  );
  AND _23_ (
    .A(_00_),
    .B(a[1]),
    .Y(_06_)
  );
  OR _24_ (
    .A(_05_),
    .B(_06_),
    .Y(y[1])
  );
  AND _25_ (
    .A(sel),
    .B(b[0]),
    .Y(_07_)
  );
  AND _26_ (
    .A(_00_),
    .B(a[0]),
    .Y(_08_)
  );
  OR _27_ (
    .A(_07_),
    .B(_08_),
    .Y(y[0])
  );
  AND _28_ (
    .A(sel),
    .B(b[6]),
    .Y(_09_)
  );
  AND _29_ (
    .A(_00_),
    .B(a[6]),
    .Y(_10_)
  );
  OR _30_ (
    .A(_09_),
    .B(_10_),
    .Y(y[6])
  );
  AND _31_ (
    .A(sel),
    .B(b[5]),
    .Y(_11_)
  );
  AND _32_ (
    .A(_00_),
    .B(a[5]),
    .Y(_12_)
  );
  OR _33_ (
    .A(_11_),
    .B(_12_),
    .Y(y[5])
  );
  AND _34_ (
    .A(sel),
    .B(b[4]),
    .Y(_13_)
  );
  AND _35_ (
    .A(_00_),
    .B(a[4]),
    .Y(_14_)
  );
  OR _36_ (
    .A(_13_),
    .B(_14_),
    .Y(y[4])
  );
endmodule
