/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mux28.v:2.1-16.10" */
module mux28(out, a, b, c, d, s0, s1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  /* src = "mux28.v:4.11-4.12" */
  input a;
  wire a;
  /* src = "mux28.v:4.14-4.15" */
  input b;
  wire b;
  /* src = "mux28.v:4.17-4.18" */
  input c;
  wire c;
  /* src = "mux28.v:4.20-4.21" */
  input d;
  wire d;
  /* src = "mux28.v:3.12-3.15" */
  output out;
  wire out;
  /* src = "mux28.v:4.23-4.25" */
  input s0;
  wire s0;
  /* src = "mux28.v:4.27-4.29" */
  input s1;
  wire s1;
  not _10_ (
    .A(s1),
    .Y(_08_)
  );
  not _11_ (
    .A(s0),
    .Y(_09_)
  );
  AND _12_ (
    .A(s0),
    .B(d),
    .Y(_00_)
  );
  AND _13_ (
    .A(_09_),
    .B(c),
    .Y(_01_)
  );
  OR _14_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  AND _15_ (
    .A(s1),
    .B(_02_),
    .Y(_03_)
  );
  AND _16_ (
    .A(s0),
    .B(b),
    .Y(_04_)
  );
  AND _17_ (
    .A(_09_),
    .B(a),
    .Y(_05_)
  );
  OR _18_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  AND _19_ (
    .A(_08_),
    .B(_06_),
    .Y(_07_)
  );
  OR _20_ (
    .A(_03_),
    .B(_07_),
    .Y(out)
  );
endmodule
