/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "mux9.v:3.1-14.10" */
module mux9(a, b, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  /* src = "mux9.v:3.26-3.27" */
  input [1:0] a;
  wire [1:0] a;
  /* src = "mux9.v:3.29-3.30" */
  input [1:0] b;
  wire [1:0] b;
  /* src = "mux9.v:4.19-4.22" */
  input sel;
  wire sel;
  /* src = "mux9.v:5.30-5.31" */
  output [1:0] y;
  wire [1:0] y;
  not _05_ (
    .A(sel),
    .Y(_03_)
  );
  AND _06_ (
    .A(sel),
    .B(b[1]),
    .Y(_04_)
  );
  AND _07_ (
    .A(_03_),
    .B(a[1]),
    .Y(_00_)
  );
  OR _08_ (
    .A(_04_),
    .B(_00_),
    .Y(y[1])
  );
  AND _09_ (
    .A(sel),
    .B(b[0]),
    .Y(_01_)
  );
  AND _10_ (
    .A(_03_),
    .B(a[0]),
    .Y(_02_)
  );
  OR _11_ (
    .A(_01_),
    .B(_02_),
    .Y(y[0])
  );
endmodule
