/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "nand16.v:2.1-10.10" */
module nand16(a, b, out);
  wire _0_;
  wire _1_;
  /* src = "nand16.v:3.22-3.23" */
  input [1:0] a;
  wire [1:0] a;
  /* src = "nand16.v:4.22-4.23" */
  input [1:0] b;
  wire [1:0] b;
  /* src = "nand16.v:5.23-5.26" */
  output [1:0] out;
  wire [1:0] out;
  AND _2_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_0_)
  );
  not _3_ (
    .A(_0_),
    .Y(out[0])
  );
  AND _4_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_1_)
  );
  not _5_ (
    .A(_1_),
    .Y(out[1])
  );
endmodule
