/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "nor17.v:2.1-10.10" */
module nor17(a, b, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  /* src = "nor17.v:3.22-3.23" */
  input [7:0] a;
  wire [7:0] a;
  /* src = "nor17.v:4.22-4.23" */
  input [7:0] b;
  wire [7:0] b;
  /* src = "nor17.v:5.23-5.26" */
  output [7:0] out;
  wire [7:0] out;
  OR _08_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_00_)
  );
  not _09_ (
    .A(_00_),
    .Y(out[3])
  );
  OR _10_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_01_)
  );
  not _11_ (
    .A(_01_),
    .Y(out[4])
  );
  OR _12_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_02_)
  );
  not _13_ (
    .A(_02_),
    .Y(out[5])
  );
  OR _14_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_03_)
  );
  not _15_ (
    .A(_03_),
    .Y(out[6])
  );
  OR _16_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_04_)
  );
  not _17_ (
    .A(_04_),
    .Y(out[7])
  );
  OR _18_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_05_)
  );
  not _19_ (
    .A(_05_),
    .Y(out[0])
  );
  OR _20_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_06_)
  );
  not _21_ (
    .A(_06_),
    .Y(out[1])
  );
  OR _22_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_07_)
  );
  not _23_ (
    .A(_07_),
    .Y(out[2])
  );
endmodule
