/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "nor28.v:3.1-25.10" */
module nor28(a, b, c, d, e, f, g, h, a1, b1, c1, d1, e1, f1, g1, h1, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  /* src = "nor28.v:4.9-4.10" */
  input a;
  wire a;
  /* src = "nor28.v:12.9-12.11" */
  input a1;
  wire a1;
  /* src = "nor28.v:5.9-5.10" */
  input b;
  wire b;
  /* src = "nor28.v:13.9-13.11" */
  input b1;
  wire b1;
  /* src = "nor28.v:6.9-6.10" */
  input c;
  wire c;
  /* src = "nor28.v:14.9-14.11" */
  input c1;
  wire c1;
  /* src = "nor28.v:7.9-7.10" */
  input d;
  wire d;
  /* src = "nor28.v:15.9-15.11" */
  input d1;
  wire d1;
  /* src = "nor28.v:8.9-8.10" */
  input e;
  wire e;
  /* src = "nor28.v:16.9-16.11" */
  input e1;
  wire e1;
  /* src = "nor28.v:9.9-9.10" */
  input f;
  wire f;
  /* src = "nor28.v:17.9-17.11" */
  input f1;
  wire f1;
  /* src = "nor28.v:10.9-10.10" */
  input g;
  wire g;
  /* src = "nor28.v:18.9-18.11" */
  input g1;
  wire g1;
  /* src = "nor28.v:11.9-11.10" */
  input h;
  wire h;
  /* src = "nor28.v:19.9-19.11" */
  input h1;
  wire h1;
  /* src = "nor28.v:20.10-20.13" */
  output out;
  wire out;
  OR _16_ (
    .A(e1),
    .B(f1),
    .Y(_00_)
  );
  OR _17_ (
    .A(h),
    .B(c1),
    .Y(_01_)
  );
  OR _18_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  OR _19_ (
    .A(d),
    .B(g),
    .Y(_03_)
  );
  OR _20_ (
    .A(a),
    .B(b),
    .Y(_04_)
  );
  OR _21_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  OR _22_ (
    .A(_02_),
    .B(_05_),
    .Y(_06_)
  );
  not _23_ (
    .A(_06_),
    .Y(_07_)
  );
  OR _24_ (
    .A(d1),
    .B(g1),
    .Y(_08_)
  );
  OR _25_ (
    .A(a1),
    .B(b1),
    .Y(_09_)
  );
  OR _26_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  OR _27_ (
    .A(e),
    .B(f),
    .Y(_11_)
  );
  OR _28_ (
    .A(h1),
    .B(c),
    .Y(_12_)
  );
  OR _29_ (
    .A(_11_),
    .B(_12_),
    .Y(_13_)
  );
  OR _30_ (
    .A(_10_),
    .B(_13_),
    .Y(_14_)
  );
  not _31_ (
    .A(_14_),
    .Y(_15_)
  );
  AND _32_ (
    .A(_07_),
    .B(_15_),
    .Y(out)
  );
endmodule
