/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "or19.v:2.1-16.10" */
module or19(a, b, out);
  /* src = "or19.v:3.11-3.12" */
  input a;
  wire a;
  /* src = "or19.v:4.11-4.12" */
  input b;
  wire b;
  /* src = "or19.v:5.12-5.15" */
  output out;
  wire out;
  OR _0_ (
    .A(a),
    .B(b),
    .Y(out)
  );
endmodule
