/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "pe20.v:1.1-11.10" */
module pe20(i, o, v);
  wire _0_;
  wire _1_;
  /* src = "pe20.v:3.17-3.18" */
  input [3:0] i;
  wire [3:0] i;
  /* src = "pe20.v:4.18-4.19" */
  output [1:0] o;
  wire [1:0] o;
  /* src = "pe20.v:5.12-5.13" */
  output v;
  wire v;
  not _2_ (
    .A(i[2]),
    .Y(_0_)
  );
  AND _3_ (
    .A(_0_),
    .B(i[1]),
    .Y(_1_)
  );
  OR _4_ (
    .A(i[3]),
    .B(_1_),
    .Y(o[0])
  );
  OR _5_ (
    .A(i[2]),
    .B(i[3]),
    .Y(o[1])
  );
  OR _6_ (
    .A(i[0]),
    .B(o[1]),
    .Y(v)
  );
endmodule
