/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "pe2.v:1.1-12.10" */
module pe2(en, i, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  /* src = "pe2.v:3.11-3.13" */
  input en;
  wire en;
  /* src = "pe2.v:4.16-4.17" */
  input [7:0] i;
  wire [7:0] i;
  /* src = "pe2.v:5.17-5.18" */
  output [2:0] y;
  wire [2:0] y;
  AND _06_ (
    .A(i[7]),
    .B(en),
    .Y(_00_)
  );
  OR _07_ (
    .A(i[6]),
    .B(_00_),
    .Y(_01_)
  );
  OR _08_ (
    .A(i[4]),
    .B(i[5]),
    .Y(_02_)
  );
  OR _09_ (
    .A(_01_),
    .B(_02_),
    .Y(y[2])
  );
  OR _10_ (
    .A(i[2]),
    .B(i[3]),
    .Y(_03_)
  );
  OR _11_ (
    .A(_01_),
    .B(_03_),
    .Y(y[1])
  );
  OR _12_ (
    .A(i[3]),
    .B(i[1]),
    .Y(_04_)
  );
  OR _13_ (
    .A(_00_),
    .B(_04_),
    .Y(_05_)
  );
  OR _14_ (
    .A(i[5]),
    .B(_05_),
    .Y(y[0])
  );
endmodule
