/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "pe6.v:1.1-12.10" */
module pe6(i, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  /* src = "pe6.v:3.16-3.17" */
  input [7:0] i;
  wire [7:0] i;
  /* src = "pe6.v:4.17-4.18" */
  output [2:0] y;
  wire [2:0] y;
  OR _05_ (
    .A(_00_),
    .B(_01_),
    .Y(y[2])
  );
  OR _06_ (
    .A(i[2]),
    .B(i[3]),
    .Y(_03_)
  );
  OR _07_ (
    .A(_02_),
    .B(_03_),
    .Y(y[1])
  );
  OR _08_ (
    .A(i[3]),
    .B(i[1]),
    .Y(_04_)
  );
  OR _09_ (
    .A(_00_),
    .B(_04_),
    .Y(y[0])
  );
  OR _10_ (
    .A(i[5]),
    .B(i[7]),
    .Y(_00_)
  );
  OR _11_ (
    .A(i[4]),
    .B(i[6]),
    .Y(_01_)
  );
  OR _12_ (
    .A(i[6]),
    .B(i[7]),
    .Y(_02_)
  );
endmodule
