/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "sub11.v:2.1-27.10" */
module sub11(A, B, D, Bout);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "sub11.v:4.11-4.12" */
  input A;
  wire A;
  /* src = "sub11.v:4.13-4.14" */
  input B;
  wire B;
  /* src = "sub11.v:5.18-5.22" */
  output Bout;
  wire Bout;
  /* src = "sub11.v:5.16-5.17" */
  output D;
  wire D;
  not _3_ (
    .A(A),
    .Y(_0_)
  );
  not _4_ (
    .A(B),
    .Y(_1_)
  );
  AND _5_ (
    .A(_0_),
    .B(B),
    .Y(Bout)
  );
  AND _6_ (
    .A(A),
    .B(_1_),
    .Y(_2_)
  );
  OR _7_ (
    .A(Bout),
    .B(_2_),
    .Y(D)
  );
endmodule
