/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "xnor5.v:1.1-9.10" */
module xnor5(a, b, out);
  wire _0_;
  wire _1_;
  wire _2_;
  /* src = "xnor5.v:2.16-2.17" */
  input a;
  wire a;
  /* src = "xnor5.v:3.16-3.17" */
  input b;
  wire b;
  /* src = "xnor5.v:4.17-4.20" */
  output out;
  wire out;
  OR _3_ (
    .A(a),
    .B(b),
    .Y(_0_)
  );
  not _4_ (
    .A(_0_),
    .Y(_1_)
  );
  AND _5_ (
    .A(a),
    .B(b),
    .Y(_2_)
  );
  OR _6_ (
    .A(_1_),
    .B(_2_),
    .Y(out)
  );
endmodule
