/* Generated by Yosys 0.41+83 (git sha1 7045cf509, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

/* cells_not_processed =  1  */
/* src = "xnor24.v:2.1-10.10" */
module xnor24(a, b, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  /* src = "xnor24.v:3.22-3.23" */
  input [3:0] a;
  wire [3:0] a;
  /* src = "xnor24.v:4.22-4.23" */
  input [3:0] b;
  wire [3:0] b;
  /* src = "xnor24.v:5.23-5.26" */
  output [3:0] out;
  wire [3:0] out;
  not _12_ (
    .A(_03_),
    .Y(_04_)
  );
  AND _13_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_05_)
  );
  OR _14_ (
    .A(_04_),
    .B(_05_),
    .Y(out[1])
  );
  OR _15_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_06_)
  );
  not _16_ (
    .A(_06_),
    .Y(_07_)
  );
  AND _17_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_08_)
  );
  OR _18_ (
    .A(_07_),
    .B(_08_),
    .Y(out[2])
  );
  OR _19_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_09_)
  );
  not _20_ (
    .A(_09_),
    .Y(_10_)
  );
  AND _21_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_11_)
  );
  OR _22_ (
    .A(_10_),
    .B(_11_),
    .Y(out[3])
  );
  OR _23_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  not _24_ (
    .A(_00_),
    .Y(_01_)
  );
  AND _25_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_02_)
  );
  OR _26_ (
    .A(_01_),
    .B(_02_),
    .Y(out[0])
  );
  OR _27_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_03_)
  );
endmodule
